### ISSUE TITLE
Differences between zitiLogin and ziti edge login

### ISSUE THREAD

**Issue by gooseleggs** [openziti/ziti#1022]
I am using this through Docker, but don't expect there to be any difference that if using it normally installed.

I need to specify the password upon logging into ziti command line.  There are two ways to log into the controller: `zitiLogin` and `ziti edge login`, however `zitiLogin` is not working as expected.

when I run `zitiLogin --help` I am given the normal help string, which contains this
```
  -p, --password string       password to use for authenticating to the Ziti Edge Controller, if -u is supplied and -p is not, a value will be prompted for
``` 

However, trying to use it, as in `zitiLogin -u admin` returns immediately with
```
ziti@3dda158774b5:/persistent$ zitiLogin -u admin
error: unable to authenticate to https://ziticontroller:443/edge/management/v1. Status code: 401 Unauthorized, Server returned: {
    "error": {
        "code": "INVALID_AUTH",
        "message": "The authentication request failed",
        "requestId": "wZZTUF7AE"
    },
    "meta": {
        "apiEnrollmentVersion": "0.0.1",
        "apiVersion": "0.0.1"
    }
}
```

If I use `ziti edge login -u admin` I am then prompted for the password.
```
Using controller url: https://ziticontwroller:443/edge/management/v1 from identity 'default' in config file: /persistent/ziti-cli.json
Enter password:
Token: b05a7c3f-0027-4567-9009-495408ffe24e
Saving identity 'default' to /persistent/ziti-cli.json
```

`zitiLogin` I understand should mimic the behavior of `ziti edge login`

**Comment by dovholuknf** [comment]
I bet and you're running into this issue
https://github.com/openziti/ziti/issues/1013

The only way to fix this right now is to save the password in a different way. It's getting overwritten in the env file each time the image/container spins up. 

zitiLogin is just a convince alias provided in the .env file. If you look at it, you'll see it is simply calling ziti edge login with the -p and -u flags. The problem with zitiLogin right now is that bug... 

Until it's fixed, you either need to source/export ZITI_PWD using some other mechanism (then zitiLogin will work again) or just issue ziti edge login instead.

Hth
