### ISSUE TITLE
Resulticks-OpenZiti Project

### ISSUE THREAD

**Issue by ResulticksInc** [openziti/ziti#1037]
o	Project Name - Resulticks
o	Link to the project site - https://www.resulticks.com/
o	Description of project - Resulticks Zero Trust API delivery network which forms the core of Resulticks' omnichannel marketing automation platform is built on OpenZiti to form a private dark mesh network.
o	Link to logo - https://www.resulticks.com/assets/platform/logos/resulticks-logo-blue.svg

**Comment by dovholuknf** [comment]
Thanks @ResulticksInc, I'll put up a pr for the adopters.md page and we'll get that merged

**Comment by surennaidu** [comment]
Thank you @ResulticksInc for being part of the journey with Ziti. More to come!

**Comment by dovholuknf** [comment]
when merged, it will appear like this:
![image](https://user-images.githubusercontent.com/46322585/225312203-fc025432-9e19-43a7-a1bf-28758fb05c0b.png)
