### ISSUE TITLE
hasEdgeRouterConnection is false, even though my endpoint is online and able to access services

### ISSUE THREAD

**Issue by tburtchell** [openziti/ziti#1093]
Environment:

OS:  Mac Ventura
Processor: Apple M2
Edge:  Desktop Edge for Mac version 2.31 (482)

Network is MOP hosted Mattermost network.  Ziti version 0.27.9.

Issue:
I am able to connect via the desktop edge and pass traffic to mattermost just fine.   
Ziti is reporting that my identity has an api session, but does not have an edge router connection

What I've tried:
* restarting the desktop edge
* disabling MFA

Ziti report of my identity:
` ze list identities 'name="mattermost.tod.burtchell.mac"' -j`

```
{
    "data": [
        {
            "_links": {
                "auth-policies": {
                    "href": "./auth-policies/default"
                },
                "authenticators": {
                    "href": "./identities/5NM2Thiq5h/authenticators"
                },
                "edge-router-policies": {
                    "href": "./identities/5NM2Thiq5h/edge-router-policies"
                },
                "edge-routers": {
                    "href": "./identities/5NM2Thiq5h/edge-routers"
                },
                "enrollments": {
                    "href": "./identities/5NM2Thiq5h/enrollments"
                },
                "failed-service-requests": {
                    "href": "./identities/5NM2Thiq5h/failed-service-requests"
                },
                "posture-data": {
                    "href": "./identities/5NM2Thiq5h/posture-data"
                },
                "self": {
                    "href": "./identities/5NM2Thiq5h"
                },
                "service-configs": {
                    "href": "./identities/5NM2Thiq5h/service-configs"
                },
                "service-policies": {
                    "href": "./identities/5NM2Thiq5h/service-policies"
                },
                "services": {
                    "href": "./identities/5NM2Thiq5h/services"
                }
            },
            "createdAt": "2023-03-07T20:39:09.120Z",
            "id": "5NM2Thiq5h",
            "tags": {},
            "updatedAt": "2023-04-19T17:09:37.442Z",
            "appData": {},
            "authPolicy": {
                "_links": {
                    "self": {
                        "href": "./auth-policies/default"
                    }
                },
                "entity": "auth-policies",
                "id": "default",
                "name": "Default"
            },
            "authPolicyId": "default",
            "authenticators": {
                "cert": {
                    "fingerprint": "c83f1b73d1511b2e6e015aa6155b6a6fd6852a87",
                    "id": "Vu32T2XqB"
                }
            },
            "defaultHostingCost": 0,
            "defaultHostingPrecedence": "default",
            "disabled": false,
            "enrollment": {},
            "envInfo": {
                "arch": "arm64",
                "os": "Darwin",
                "osRelease": "22.4.0",
                "osVersion": "Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:58 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6020"
            },
            "externalId": null,
            "hasApiSession": true,
            "hasEdgeRouterConnection": false,
            "isAdmin": false,
            "isDefaultAdmin": false,
            "isMfaEnabled": false,
            "name": "mattermost.tod.burtchell.mac",
            "roleAttributes": [
                "client"
            ],
            "sdkInfo": {
                "appId": "io.netfoundry.ZitiPacketTunnel.PacketTunnelProvider",
                "appVersion": "2.31 (482)",
                "branch": "HEAD",
                "revision": "68c3a76",
                "type": "ziti-sdk-c",
                "version": "0.31.4"
            },
            "serviceHostingCosts": {},
            "serviceHostingPrecedences": {},
            "type": {
                "_links": {
                    "self": {
                        "href": "./identity-types/Device"
                    }
                },
                "entity": "identity-types",
                "id": "Device",
                "name": "Device"
            },
            "typeId": "Device"
        }
    ],
    "meta": {
        "filterableFields": [
            "id",
            "createdAt",
            "updatedAt",
            "tags",
            "isSystem",
            "name",
            "externalId",
            "type",
            "isAdmin",
            "roleAttributes",
            "authPolicyId",
            "isDefaultAdmin"
        ],
        "pagination": {
            "limit": 10,
            "offset": 0,
            "totalCount": 1
        }
    }
}
```

**Comment by NetFoundry-Zendesk** [comment]
<div class="panel panel-warning" style="border-color: #faebcc;margin-bottom: 20px;background-color: #fff;border: 1px solid transparent;border-radius: 4px;-webkit-box-shadow: 0 1px 1px rgb(0 0 0 / 5%);box-shadow: 0 1px 1px rgb(0 0 0 / 5%);font-size: 14px;">
                <div class="panel-heading" style="color: #8a6d3b;background-color: #fcf8e3;border-color: #faebcc;padding: 10px 15px;border-bottom: 1px solid transparent;border-top-left-radius: 3px;border-top-right-radius: 3px;">Comment from Zendesk:</div>
                <div class="panel-body" style="padding: 15px;">
                  <strong>Zendesk:&nbsp;</strong><a href="https://netfoundry.zendesk.com/agent/tickets/10903" target="_blank">10903</a>&nbsp;linked successfully.
                </div>
                <div class="panel-footer" style="padding: 10px 15px;background-color: #f5f5f5;border-top: 1px solid #ddd;border-bottom-right-radius: 3px;border-bottom-left-radius: 3px;">
                  Zendesk:&nbsp;<a href="https://netfoundry.zendesk.com/agent/tickets/10903" target="_blank">#10903</a>
                  <div class="pull-right" style="float:right">By: <em>Ganesh Palaniappan &lt;ganesh.palaniappan@netfoundry.io&gt;</em></div>
                </div>
              </div>

**Comment by NetFoundry-Zendesk** [comment]
<div class="panel panel-warning" style="border-color: #faebcc;margin-bottom: 20px;background-color: #fff;border: 1px solid transparent;border-radius: 4px;-webkit-box-shadow: 0 1px 1px rgb(0 0 0 / 5%);box-shadow: 0 1px 1px rgb(0 0 0 / 5%);font-size: 14px;">
                <div class="panel-heading" style="color: #8a6d3b;background-color: #fcf8e3;border-color: #faebcc;padding: 10px 15px;border-bottom: 1px solid transparent;border-top-left-radius: 3px;border-top-right-radius: 3px;">Comment from Zendesk:</div>
                <div class="panel-body" style="padding: 15px;">
                  <strong>Zendesk:&nbsp;</strong><a href="https://netfoundry.zendesk.com/agent/tickets/10921" target="_blank">10921</a>&nbsp;linked successfully.
                </div>
                <div class="panel-footer" style="padding: 10px 15px;background-color: #f5f5f5;border-top: 1px solid #ddd;border-bottom-right-radius: 3px;border-bottom-left-radius: 3px;">
                  Zendesk:&nbsp;<a href="https://netfoundry.zendesk.com/agent/tickets/10921" target="_blank">#10921</a>
                  <div class="pull-right" style="float:right">By: <em>Ganesh Palaniappan &lt;ganesh.palaniappan@netfoundry.io&gt;</em></div>
                </div>
              </div>
