### ISSUE TITLE
Make ziti cmd into a shell and pull edge controller pieces back into ziti-edge

### ISSUE THREAD

**Issue by plorenz** [openziti/ziti#11]
This will also allow ziti fabric pieces to be plugged into the ziti shell.

**Comment by andrewpmartinez** [comment]
This should also allow the CLI to easily use and be lockstep versioned w/ the swagger/open-api2 client.

**Comment by qrkourier** [comment]
I'm very interested in this lockstep relationship between client and server you mentioned @andrewpmartinez . I need to learn how to do this for the NetFoundry CLI+API too. To start I want to be able to create entity templates for creating new identities with the CLI by referencing the OpenAPI spec from the NF platform API.

**Comment by plorenz** [comment]
This was made redundant by the merge of edge and fabric into ziti
