### ISSUE TITLE
Handle GITHUB errors in quickstart

### ISSUE THREAD

**Issue by gberl002** [openziti/ziti#1122]
When making an API call, with or without `GITHUB_TOKEN`, if there is an issue, the quickstart script does not handle the error and continues with the install.

This can occur in the following known situations (when `ZITI_VERSION_OVERRIDE` is not set):

- When the `GITHUB_TOKEN` is expired or incorrect
- When the API request limit has been reached (typically when `GITHUB_TOKEN` is not set)

Here is an example of such a failure
![image](https://github.com/openziti/ziti/assets/95235264/e5c9f5b3-92f0-4bf4-bb6d-f53e86c3ee23)

The version comes back as `null`. There is already an example of handling this error in the `verifyZitiVersionExists` function, however, that function is only used when `ZITI_VERSION_OVERRIDE` is used where it will confirm a version exists before proceeding to download it, otherwise the version is stripped from `.../releases/latest`.

This issue can be easily reproduced by setting `GITHUB_TOKEN` to some invalid token value before calling `getZiti` or running `expressInstall`

**Comment by smilindave26** [comment]
deprecated for alt quickstart approach `ziti edge quickstart`
