### ISSUE TITLE
Edge Router: Support multiple protocols on the same listener port

### ISSUE THREAD

**Issue by tburtchell** [openziti/ziti#1135]
I would like to be able to use the same port for multiple protocols.  For example, when I host an edge router today I need up to three ports:
80 - fabric link listener
443 - edge TLS listener
7001 - edge WSS listener

I would dearly love to be able to use only one port for all three types of traffic.  Two ports - 80 for link and 443 for all edge would be good enough, too.

**Comment by dovholuknf** [comment]
If we decided to go ALPN, I'd like to see us write this up with why how and what we ended up doing as part of this...
