### ISSUE TITLE
Quickstart: Support external IP

### ISSUE THREAD

**Issue by jlin-nf** [openziti/ziti#1141]
Currently, if user want to use external IP (instead of external DNS) when creating NC with quickstart, he has to set environmental variable: EXTERNAL_DNS to an IP:

i.e. export EXTERNAL_DNS="34.30.50.57"

This step, puts the IP address into the SANs as DNS:

X509v3 Subject Alternative Name:
            DNS:testpubcloud-nc, DNS:localhost, DNS:testpubcloud-nc, DNS:34.30.50.57, 

Would like to request a better and cleaner ways for user to create NC with external IP.

**Comment by smilindave26** [comment]
already addressed per @qrkourier
