### ISSUE TITLE
Multiport service

### ISSUE THREAD

**Issue by wangzy1065** [openziti/ziti#1143]
When I have an application service that uses multiple ports, does Ziti support it? If supported, how would you like to configure it?

**Comment by dovholuknf** [comment]
I assume here you are referring to "tunnelers" and not application embedded, right? Application embedded, you of course can do whatever you want and ports might (or might not) be relevant...

Assuming you're talking about tunnelers, when making the "intecept.v1" config you have the option to specify multiple ports. You can see an example on our doc page here: https://docs.openziti.io/docs/learn/core-concepts/config-store/config-type-intercept-v1/

It is using a low/high port of 5000, but you can make the low 4000 and the hight 6000 for example... Also notice it's an array. You can specify more than one range as well in the same intercept as shown below as an example. I'm gonna close this as answered. :)

```
{
    "protocols": [
        "tcp"
    ],
    "addresses": [
        "acme.example.ziti"
    ],
    "portRanges": [
        {
            "low": 500,
            "high": 5000
        },
        {
            "low": 15000,
            "high": 25000
        }
    ]
}
```

**Comment by wangzy1065** [comment]
Thank you for your answer, my service is in the company intranet, I need to open port 80,443,5666,18002, many times I need to access this service at home

**Comment by wangzy1065** [comment]
what i do now is to set intecept.v1 to specify multiple ports as above, and then set multiple terminating routers to edge_transport tcp:192.168.0.10:80,edge_transport tcp:192.168.0.10:443,edge_transport tcp :192.168.0.10:5666,edge_transport tcp:192.168.0.10:18002, after this setting, access to this service is failed, or there is another way to configure, Please tell me how to configure it. Please

**Comment by wangzy1065** [comment]
Thank you very much. My problem has been resolved, and I hope your company is getting better and better
