### ISSUE TITLE
external CA roles based on SPIFFE ID

### ISSUE THREAD

**Issue by qrkourier** [openziti/ziti#1148]
There's one set of default roles added to all auto-enrolled identities from an external CA. This means I need a separate CA for each distinct set of identity roles.

A hypothetical feature of Ziti external CAs is parsing roles from the SPIFFE ID.

A simplistic implementation could treat a particular position in the SPIFFE ID as a Ziti identity role, e.g., `spiffe://{{trust domain}}/workloads/{{ entity name }}/role/{{ role name }}`. A more sophisticated implementation could introduce a new type of identity role which is an SVID match pattern.

**Comment by qrkourier** [comment]
Found this relevant doc: https://docs.openziti.io/docs/learn/core-concepts/security/authentication/third-party-cas/#external-id--x509-claims

**Comment by qrkourier** [comment]
One solution is to use the external CA enrollment method `ottca` to pre-create identities with particular attributes, then match (re-use) that identity by `externalId`. Put another way, the SVID can be automatically matched to a persistent OpenZiti Identity. That way, there's no need to garbage collect a proliferation of auto-enrolled identities from each run of a SPIFFE-enabled pod.

**Comment by smilindave26** [comment]
Similar requests have come up for roles based on OIDC claims property that we will implement, will revisit this if future external demand
