### ISSUE TITLE
About the configuration method of using openziti access for webrtc services

### ISSUE THREAD

**Issue by wangzy1065** [openziti/ziti#1178]
I would like to ask about the configuration method for using Openziti access for webrtc services

My current configuration method is:[](https://openziti.io/docs/guides/Local_Gateway/EdgeTunnel)

**Comment by wangzy1065** [comment]
https://openziti.io/docs/guides/Local_Gateway/EdgeTunnel

**Comment by dovholuknf** [comment]
I'm persnonally not an expert on webrtc and I'm not sure how it'd play in an OpenZiti type of landscape. For example, if you are using OpenZiti tunnelers, is there even a need for webrtc when you can "just connect" to the target? I don't know if anyone has tried any webrtc type things, I know I haven't... So short answer is, I just don't know. Maybe someone else has had experience trying it.
