### ISSUE TITLE
support alt-server-certs in config creation

### ISSUE THREAD

**Issue by dovholuknf** [openziti/ziti#1179]
It'd be nice to have the quickstart allow specifying alt-server-certs for situations when there is a legitimate cert to be used such as in browzer installs.

**Add the following variables:**
* ZITI_ALT_SERVER_ADDRESS
* ZITI_ALT_SERVER_CERT
* ZITI_ALT_SERVER_KEY

**Business/verification rules:**
* All three must be supplied in order for `ZITI_ALT_SERVER_*` configuration to work. If only 1 or 2 are supplied a warning should be shown indicating alt server certs was not configured.
* `ZITI_ALT_SERVER_ADDRESS` **MUST NOT** overlap with `ZITI_CTRL_EDGE_ADVERTISED_ADDRESS`. If the two values are identical, show an error indicating the problem and exit, probably cleaning up after the error (unsetting vars, removing files etc.?)
* When supplied, `ZITI_ALT_SERVER_ADDRESS` should be used everywhere `ZITI_CTRL_EDGE_ADVERTISED_ADDRESS` used to be used **except** in PKI creation, as noted above
* Do not add the alt_server_block to the root identity section, allow the control plane to use the 'internal' pki
* in router config creation, `ZITI_ALT_SERVER_ADDRESS`  overrides `ZITI_ROUTER_ADVERTISED_ADDRESS`. if both are set display an info message indicating both were supplied and `ZITI_ALT_SERVER_ADDRESS` was used

**Comment by qrkourier** [comment]
This was done.

Set these to the file paths for `ziti create config controller`:
- `ZITI_PKI_ALT_SERVER_CERT`
- `ZITI_PKI_ALT_SERVER_KEY`

```go
identity:
  cert:        "{{ .Controller.Identity.Cert }}"
  server_cert: "{{ .Controller.Identity.ServerCert }}"
  key:         "{{ .Controller.Identity.Key }}"
  ca:          "{{ .Controller.Identity.Ca }}"
  {{ if not .Controller.Web.Identity.AltCertsEnabled }}#{{ end }}alt_server_certs:
  {{ if not .Controller.Web.Identity.AltCertsEnabled }}#{{ end }}  - server_cert:  "{{ .Controller.Web.Identity.AltServerCert }}"
  {{ if not .Controller.Web.Identity.AltCertsEnabled }}#{{ end }}    server_key:   "{{ .Controller.Web.Identity.AltServerKey }}"
```
