### ISSUE TITLE
Kali linux doesn't seem to work with quickstart

### ISSUE THREAD

**Issue by dovholuknf** [openziti/ziti#1186]
see https://openziti.discourse.group/t/quickstart-authentication-req-failed-local-no-docker/1345

Something about Kali is causing the quickstart to fail. Investigate and figure out why

**Comment by plorenz** [comment]
Was closed when edge was merge to ziti and a commit comment referencing an edge issue now referenced this issue. Reopening.

**Comment by ekoby** [comment]
closing, use embedded quickstart
