### ISSUE TITLE
make web[].identity.server_cert optional

### ISSUE THREAD

**Issue by qrkourier** [openziti/ziti#1208]
Ziti controller config property `identity.server_cert` is optional [as documented](https://openziti.io/docs/reference/configuration/conventions/#identity), but `web[].identity.server_cert` is required in Ziti 0.29.0. 

Proposal for the sake of consistency: change the `web[].identity` logic in Ziti controller to use `web[].identity.cert` as the server certificate unless `web[].identity.server_cert` is defined.

When this is fixed, the controller will stop emitting this message when `web[].identity.cert` is defined and `web[].identity.server_cert` is not defined.

```
ziti-controller panic: error parsing web configuration [web] at index [0]: error parsing identity section: error parsing identity: required configuration value [web.identity.server_cert] is missing or is blank                                                                                                                           
```

**Comment by andrewpmartinez** [comment]
This touched the validation code in the identity framework that will affect xweb as a result.

xweb's intention is to host HTTP/HTTPs servers and thus should not allow certs not meant for hosting HTTP servers. The identity libraries validation needs to be amended and replaceable. xweb should use the identity validation facilities but then extend them by validating certificate flags to ensure they are minimally valid for modern HTTP clients.

xweb will be used to host OIDC functionality and thus will involve browsers hitting xweb-configured facilities. Meaning, ensuring that server certificates are properly configured is important to the new authentication flows that HA is bringing.

**Comment by qrkourier** [comment]
`identity.server_cert` is required when `identity` appears in a configuration context that is only used as a TLS server, e.g., the controller or router `web[]` listeners.
