### ISSUE TITLE
Idea / feature request: consider alternative authentication mechanism for client onboarding to JWT

### ISSUE THREAD

**Issue by qdrddr** [openziti/ziti#1258]
For the client (OpenZiti Tunneler) to access a service on the Ziti network, a JWT identity must be created on the server, and the secret jwt file must be transferred to the client to be added to the Tunneler. This creates a potential security issue when the file can be copied before it is provided to the client without the client even knowing it.

Please consider onboard clients by creating key pairs where the private key is generated on the client side and never left/transferred from the client host.

Similar to the ssh private/public keys mechanism.

An excellent example of an alternative to how it is done can be found with the ZeroTier One project, where the keys are generated on the node client side, and only public Node IDs numbers are visible and can be transferred and authenticated to the Controller. In this example, even if a client (node) knows the ZeroTier Network ID to connect, the network will see and list the new Node client but wait, allowing it to participate until an admin authorizes the new node to connect to the network via UI or API.

**Comment by smilindave26** [comment]
Hi @qdrddr - thanks for writing this issue.  The enrollment JWT is a one-time-use token, generally with a short expiration time.  You're correct that it needs to be treated as a secret.  The keys used for communication *are* generated at the endpoints and never leave that endpoint.  There is a good series of articles that outline the approach we use: https://openziti.io/blog/bootstrapping-trust/part-05.bootstrapping-trust

We also support alternate approaches that don't require the enrollment JWT at all, e.g., [Auto CA Enrollment](https://openziti.io/docs/learn/core-concepts/security/enrollment#auto-ca-enrollment) or switching to primary auth via an IdP using [External JWT Signers](https://openziti.io/docs/learn/core-concepts/security/authentication/external-jwt-signers).

**Comment by qrkourier** [comment]
There are actually two copies of that article out there, and this one is a little better connected to other articles you might find interesting: https://blog.openziti.io/bootstrapping-trust-part-5-bootstrapping-trust

**Comment by qdrddr** [comment]
If you decide to make this separately proposed improvement, https://github.com/openziti/ziti/issues/1256
Client enrollment & JWT creation can be done as part of the network enrollment proposed, similar to ZeroTier Node enrollment. 

Basically, you'll need to have Tunnerers to have functionality similar to ZeroTier, and once a network connection is established from the Tunneler to the Controller and router, you can generate JWT locally on the client.

**Comment by qdrddr** [comment]
In any way, it would be great to generate JWTs locally on the Tunneler client and skip the transfer or the file altogether without any 3rd party tools.

**Comment by ekoby** [comment]
our enrollment process follows RFC-7030 standard.

also, your process can be implemented with 3rd party CA enrollment

**Comment by ekoby** [comment]
Enrollment with IDP(oidc) feature is in #2324
