### ISSUE TITLE
quickstart: check cert chains in CI

### ISSUE THREAD

**Issue by qrkourier** [openziti/ziti#1279]

**Comment by qrkourier** [comment]
blocked by https://github.com/openziti/ziti/pull/1274 because https://github.com/openziti/ziti/pull/1278 introduces a zsh script that needs to be run inside the compose quickstart environment with quickstart env vars defined

**Comment by qrkourier** [comment]
closed unintentionally by incorrectly-labeled commit message

**Comment by ekoby** [comment]
old quickstart
