### ISSUE TITLE
quickstart_test.go is not idempotent

### ISSUE THREAD

**Issue by qrkourier** [openziti/ziti#1291]
Ziti resources may be left behind when a problem occurs while running quickstart_test.go. Subsequent runs fail because those resources are not expected to exist, and names are hard-coded and must be unique.

Alternatives include:

1. idempotency: handle existing resources and update if not matching the expected state
2. unique names per run, e.g., a randomized or serialized suffix

**Comment by qrkourier** [comment]
Although this is named "quickstart_test" it's broadly applicable to end-to-end testing, not merely quickstart networks.

**Comment by dovholuknf** [comment]
This should be closed. It's not necessary to make it rerunnable

**Comment by qrkourier** [comment]
I must have misunderstood the purpose of this test. I believed it was presumed "safe" to run on any existing network, but I if not re-runnable then it's only safe to run on a pristine, disposable network that was created for the purpose of testing.
