### ISSUE TITLE
Create Docker Compose Reentrant Test

### ISSUE THREAD

**Issue by gberl002** [openziti/ziti#1294]
It would be nice to have a test that ensures configs are not getting recreated during down/up. We've had at least two regressions relating to this in the past so a test would be highly beneficial.

`docker compose up`
Make an edit in controller and router configs (maybe check the timestamps instead, or whatever else works)
`docker compose down`
`docker compose up`
Confirm that the change made to the controller and router configs is still there

**Comment by qrkourier** [comment]
The Docker deployments are idempotent: https://openziti.io/docs/category/docker
