### ISSUE TITLE
Need a way to enroll SDK identities with IDP authentication

### ISSUE THREAD

**Issue by ekoby** [openziti/ziti#1352]
Possibly have a stable JWT for each JWT signer with all needed information -- controller address, IDP URL, etc

**Comment by smilindave26** [comment]
I'd like to include a flow where the user only needs to know a single URL, similar to what happens with BrowZer.  User can be handed that URL out-of-band.  When they hit it, the dance with IdP is kicked off.  Distributing that info in a JWT is a fine option, but hopefully not required.

**Comment by andrewpmartinez** [comment]
Also see #2324

**Comment by andrewpmartinez** [comment]
Closing as a dupe of: #2324
