### ISSUE TITLE
add hostname/domainname to EnvInfo

### ISSUE THREAD

**Issue by ekoby** [openziti/ziti#1354]
see openziti/ziti-sdk-c#537

a customer requested adding Hostname and Domainname to SdkInfo. `EnvInfo` part makes more sense me -- it should be ok as long as it can be looked up

**Comment by NetFoundry-Zendesk** [comment]
<div class="panel panel-warning" style="border-color: #faebcc;margin-bottom: 20px;background-color: #fff;border: 1px solid transparent;border-radius: 4px;-webkit-box-shadow: 0 1px 1px rgb(0 0 0 / 5%);box-shadow: 0 1px 1px rgb(0 0 0 / 5%);font-size: 14px;">
                <div class="panel-heading" style="color: #8a6d3b;background-color: #fcf8e3;border-color: #faebcc;padding: 10px 15px;border-bottom: 1px solid transparent;border-top-left-radius: 3px;border-top-right-radius: 3px;">Comment from Zendesk:</div>
                <div class="panel-body" style="padding: 15px;">
                  <strong>Zendesk:&nbsp;</strong><a href="https://netfoundry.zendesk.com/agent/tickets/10695" target="_blank">10695</a>&nbsp;linked successfully.
                </div>
                <div class="panel-footer" style="padding: 10px 15px;background-color: #f5f5f5;border-top: 1px solid #ddd;border-bottom-right-radius: 3px;border-bottom-left-radius: 3px;">
                  Zendesk:&nbsp;<a href="https://netfoundry.zendesk.com/agent/tickets/10695" target="_blank">#10695</a>
                  <div class="pull-right" style="float:right">By: <em>Christian Mark Sioson &lt;mark.sioson@netfoundry.io&gt;</em></div>
                </div>
              </div>
