### ISSUE TITLE
Allow router to decomission itself

### ISSUE THREAD

**Issue by plorenz** [openziti/ziti#1402]
Add a `ziti agent router decomission` that will ask the controller to delete the router out of the model. Useful in autoscaling setups when scaling down.

Can be used in conjunction with quiesce, see openziti/fabric#538

**Comment by dariuszSki** [comment]
@plorenz any idea when would this be implemented?

**Comment by Russell-Allen** [comment]
Does decommissioning a router result in the router being deleted from the controller, or does it just change the state of the router such that it is not used for new sessions/circuits?  Can a decommissioned router be recommissioned?

How aggressive is the decommissioning process?  Does it force existing circuits to reroute, or is it 'soft' and just prevents new usage of the router?

**Comment by plorenz** [comment]
> Does decommissioning a router result in the router being deleted from the controller, or does it just change the state of the router such that it is not used for new sessions/circuits? Can a decommissioned router be recommissioned?
> 
> How aggressive is the decommissioning process? Does it force existing circuits to reroute, or is it 'soft' and just prevents new usage of the router?

It's intended for use in scale-up/scale-down, so the router will get deleted. It's intended to be as part of a larger set of operations. 

There's already a quiesce operation, which will mark all terminators as failed. That will allow existing circuits to complete, but will only create new circuits on that router if it's the only available option. 

There still one piece not yet implemented, which is a way to check for active circuits on the router. In the end, the flow would look something like:

quiesce
wait for circuit count to drop to 0, with some timeout
decomission
