### ISSUE TITLE
ziti-cli comma+space causes unhelpful error

### ISSUE THREAD

**Issue by mikegorman-nf** [openziti/ziti#1420]
When creating a service via the CLI, if you have comma+space in the config list, rather than just a comma, there is a name parsing error, and it is unhelpful, as it says the config names aren't found when they are clearly there.  

```
ubuntu@ip-172-31-29-93:~/.ssh$ ziti edge create service iperfIreland -c iperfServer, iperfServerIreland
Found 0 configs with id or name matching
error: no configs with id or name matching
ubuntu@ip-172-31-29-93:~/.ssh$ ziti edge create service iperfIreland -c iperfServer,iperfServerIreland
New service iperfIreland created with id: 7VeTgzndhhgc2M46eFrzp3
```

**Comment by andrewpmartinez** [comment]
The space processing is going to be based on shell implementations. Talking through the issue, quoting the `-c` argument would make this valid.

What we can do is configure the command to have a specific number of expected positional arguments, which would change the error output but not make the supplied command valid.
