### ISSUE TITLE
KEO-OpenZiti Adopter

### ISSUE THREAD

**Issue by shellyKEO** [openziti/ziti#1434]
Project Name: KEOIC
Link to the project site: www.keoic.com
Description of project: KEO International Consultants is a multifaceted AEC firm with a presence across the Middle East and Europe. KEO uses the CloudZiti platform to facilitate zero-trust connections for users, devices, and applications throughout their worldwide network of branch offices and sites.
Link to the logo: https://photos.app.goo.gl/j96rH9SMUdXovRS97

**Comment by dovholuknf** [comment]
Hi @shellyKEO. Thanks for the issue! Do you have a permanent location for the logo? Perhaps https://static.wixstatic.com/media/300f00_ebca9ecefd8743eb82769e1d3079e55a~mv2.jpg is a good link ? (Admittedly, I'm a little concerned for that url's longevity)

Is this the stable location for the logo?

**Comment by shellyKEO** [comment]
Hi,
Yes, you can use that location. Thank you.

Sent from my mobile.
________________________________
