### ISSUE TITLE
ziti-router: If you modify/delete an existing service with wildcard DNS the intercept is deleted but not reinserted for any previously queried hostnames

### ISSUE THREAD

**Issue by r-caamano** [openziti/ziti#1440]
ziti-router: The first time you modify/delete an existing service with a wildcard dns as the intercept  i.e. add or remove ports then the associated tproxy rule will be deleted and not re-added for any previously queried addresses.    After querying a new host associated with the wildcard domain name tproxy entries are created, however they map to the previous tproxy port and not new tproxy listening port associated with the modified service.  Also subsequent modifications to the same service no longer modify any tproxy entries.  If you then try to delete the service, the tproxy rule is not deleted and subsequently not properly recreated if a new service is added with the same wildcard url.  This issue is not cleared unless the ziti-router process is restarted.

**Comment by ekoby** [comment]
fixed possibly, validate
