### ISSUE TITLE
Creating & Removing Terminator Loop after renaming service/configs/policies

### ISSUE THREAD

**Issue by dmuensterer** [openziti/ziti#1508]
As per https://openziti.discourse.group/t/creating-removing-terminator-loop/1772/1 there is a loop of creating and removing terminators if a service is created with according policies and configs on the identity, where the terminators are created.
I assume, this is caused by renaming service/policies/configs without restarting the tunneler on the terminator end afterwards.
Running Ziti SDK 0.35.2 with Ziti Edge Tunnel v0.22.11.

**Comment by plorenz** [comment]
Hi @dmuensterer, were you able to test this with v0.31.0+?

**Comment by ekoby** [comment]
no updates
re-open if issue re-appears.
