### ISSUE TITLE
Terraform provider or docs on recommended restapi usage

### ISSUE THREAD

**Issue by nwmcsween** [openziti/ziti#1512]
Looking to use IaC to manage openziti and so far have seen guides using the terraform restapi provider to craft api requests, wondering if openziti is looking at creating a terraform provider or if there is a "right" way of using the restapi using terraform (docs).

**Comment by qrkourier** [comment]
Clint linked you to the references for the two edge APIs: client, management. It sounds like you're looking for the management API, i.e. managing an OpenZiti network's resources with IaC. 

The `restapi` provider that I adapted to work with OpenZiti is a thin wrapper around the OpenZiti management API, so it does the bare minimum you'd expect from a TF provider, essentially translating a resource declaration into the necessary CRUD operations. It was an experiment, so not a lot of polish has gone into it.

Are you partial to Terraform, CDK, Ansible, Pulumi for IaC? The Terraform path is the best-blazed trail so far, but [the Python library for the management API](https://github.com/openziti-test-kitchen/openziti-edge-management-python#readme) is a great start toward an Ansible Collection of modules for managing OpenZiti network resources.

**Comment by ekoby** [comment]
no longer seems relevant to the project
other projects are in progress to provide similar functionality
