### ISSUE TITLE
default router policies unless init --no-router-policies

### ISSUE THREAD

**Issue by qrkourier** [openziti/ziti#1522]
Everyone who learns how to Ziti stumbles immediately on the fact that the controller does not automatically create a blanket, default ERP, and SERP.

A controller, when initializing, should always do the equivalent of these two commands unless the `--no-router-policies` flag is set.

```bash
ziti edge create edge-router-policy "all-routers" \
    --edge-router-roles '#all' --identity-roles '#all'

ziti edge create service-edge-router-policy "all-routers" \
    --edge-router-roles '#all' --service-roles '#all'
```

**Comment by ekoby** [comment]
I'd certainly prefer that quickstart created usable policies.

another option is when creating a service to check if it is accessible/usable and output a message with commands to configure policies. Something like this:
```
$ ziti edge create service super-service ...
...
Service `super-service` need policies to be accessible, here is how you can create them:

    ziti edge create service-policy ...
    ziti edge create service-edge-router-policy ...

```

**Comment by qrkourier** [comment]
Relevant console issue: https://github.com/openziti/ziti-console/issues/181

**Comment by qrkourier** [comment]
> I'd certainly prefer that quickstart created usable policies.

@ekoby You'd prefer default policies or referring users who want default policies to the quickstart? Not sure if "prefer that quickstart created" or "prefer that over quickstart-created."

**Comment by qrkourier** [comment]
@ekoby Now it seems obvious, and I agree that quickstarts should create default policies. `ziti edge quickstart` and its Docker and Kubernetes counterparts already do this. :relaxed:

**Comment by dovholuknf** [comment]
With the new "deployments" (aka prod-type), the question to me is, should THOSE do this sort of thing too? I think it's clear that the user should be prompted during intstall that some bootstrapping type script can optionally insert the policies. Kubernetes and docker are harder to do this in. Those should probably output a banner after running, showing the user exactly what to run next if they want default policies and that we __STRONGLY__ recommend them. or something like that. i don't think unattended installations need any sort of 'option' though, there shouldn't be some env var saying "BOOTSTRAP_POLICIES" - the automation should just know it's needed and do it and that should be left up to the operator

**Comment by qrkourier** [comment]
The consensus is prod deployments **shall never** create default router policies. Quickstarts already create default router policies.
