### ISSUE TITLE
Adopter Issue: Underground Nexus

### ISSUE THREAD

**Issue by Cloud-Underground** [openziti/ziti#1570]
Project Name:
Underground Nexus

Link to project site:
https://github.com/Underground-Ops/underground-nexus

How OpenZiti is used or why OpenZiti was chosen:
Cloud Underground has chosen OpenZiti to integrate with our project called the Underground Nexus. OpenZiti provides our project with a unique way to maintain Zero Trust networking using it's overlay system to produce networks that don't require applications to be exposed to the public web - without the use of a VPN.

The Underground Nexus is a hybrid cloud solution designed to allow developers to scale their projects across whatever hosting is approved or available.

The primary use cases that the Underground Nexus was originally designed for include supporting cloud functionality for datacenter resources hosted on power grids, submarines, satellites and other entities that need to maintain operation either offline or in motion where connectivity might be inconsistent or unavailable. In many cases, military clients need to maintain offline assets that do not connect to the internet.

Consumer uses for the Underground Nexus include the ability to scale compute resources seamlessly between public cloud, office on premise servers and any development servers in use on the desks or at the homes of system administrators who need access to bare metal resources. OpenZiti allows scaling, monitoring and load balancing across physical geological locations to work effortlessly.

Link to logo:
Logo is attached to this issue
![logo_grey_no_shadow](https://github.com/openziti/ziti/assets/97929868/9a3a6dea-a3ef-435b-8c37-972a5e2b036b)

**Comment by dovholuknf** [comment]
Can you provide a durable link which I can link the logo to? Thanks!

**Comment by Cloud-Underground** [comment]
Absolutely, here is a durable link to the logo in an SVG format:
https://github.com/Underground-Ops/underground-nexus/blob/main/Graphics/SVG/cloud-underground-logo.svg
