### ISSUE TITLE
ziti allows for definition of a intercept.v1 config with low port range greater than high port range

### ISSUE THREAD

**Issue by tmousawNF** [openziti/ziti#1594]
Ziti allows for the definition of an intercept.v1 config with low port range greater than high port range.

For example [step 3 in the quickstart guide](https://docs.openziti.io/docs/learn/quickstarts/services/ztha) might look something like the following for this case:
`ziti edge create config http.intercept.v1 intercept.v1 '{"protocols":["tcp"],"addresses":["http.ziti"], "portRanges":[{"low":100, "high":80}]}'`

Ziti will create this and then if you define policies to use the config, it will treat it as if the low and high values are actually swapped (i.e. low=80 and high=100).

**Comment by qrkourier** [comment]
We can close this @plorenz if it's not a problem.

**Comment by plorenz** [comment]
I agree that it would be cleaner if it were enforced, but it doesn't feel worth the effort. I'll add a revisit label, but close for now.
