### ISSUE TITLE
UDP Socket timer is too long

### ISSUE THREAD

**Issue by mikegorman-nf** [openziti/ziti#1597]
The 5 minute timer for UDP sockets to expire seems too long in some scenarios, especially when used for operations like DNS.  At scale, this means that thousands of ports can be tied up for a significant amount of time for no useful reason.  Understanding this is not true of all cases, perhaps the timer should be made configurable?

**Comment by scareything** [comment]
https://github.com/openziti/ziti/blob/main/tunnel/udp_vconn/policy.go#L61

**Comment by scareything** [comment]
I only see it documented in the [release notes](https://github.com/openziti/ziti/blob/main/changelogs/CHANGELOG.0.28.md#ert-udp-settings), but https://github.com/openziti/edge/pull/1504 made it possible to se the udp timeout in the router config file:

```json
listeners:
  - binding: tunnel
    options:
      mode: tproxy
      udpIdleTimeout: 30s
      udpCheckInterval: 30s
```

I think this capability addresses this issue exactly as written.
