### ISSUE TITLE
Redocly site 404 when edge client and management api bind different ports

### ISSUE THREAD

**Issue by sabedevops** [openziti/ziti#1606]
ziti version: `0.26.10`

Request handler for `GET https://${host}:8443/edge/management/v1/docs` attempts to access `swagger.json` at `GET  https://${host}:8443/swagger.json`, which results in a 404 as per below:

![image](https://user-images.githubusercontent.com/22971615/201730708-5379baef-f6c4-46f7-abc9-3590087b6562.png)

In particular, this happens when the edge management and client api servers bind different ports. In the case above `GET http://${host}:443/edge/client/v1/docs` still succeeds.

**Comment by qrkourier** [comment]
@dovholuknf Maybe we should move ReDocly to a generic xweb binding. This makes me wonder how ReDocly is currently handled if it's not similar to your xweb experiment for zac.

**Comment by ekoby** [comment]
works now
