### ISSUE TITLE
edge api specs for services endpoints lack configTypes paramater

### ISSUE THREAD

**Issue by sabedevops** [openziti/ziti#1607]
ziti version: `0.26.10`

`GET /services` accepts an optional parameter `configTypes` that is not currently documented in the specification but is essential for non-priviledged edge clients to request the concrete, coalesced value of the service's `config` key.

Describe: `GET /services/?configTypes=all`

It might be worth enhancing the description of the `config` definition to include commentary relating to document the identity service config override interaction.

**Comment by ekoby** [comment]
fixed
