### ISSUE TITLE
Service list/online status not updated after authenticator delete

### ISSUE THREAD

**Issue by nf-npieros** [openziti/ziti#1610]
When an enrolled identity's authenticator is deleted (via a re-enroll) the desktop client does not refresh the identity's online status or service list.

Steps to reproduce:
create an identity and give it access to one or more service
enroll the identity via the desktop client
verify the service details show up in the desktop client
re-enroll the authenticator to delete the current authenticator and generate a new enrollment

At this point, the desktop client will continue to show the services for the identity and continue to show it as enrolled until the user either manually restarts the desktop client or something else triggers a refresh.

**Comment by andrewpmartinez** [comment]
This functionality refers to legacy authentication (i.e. non-OIDC). OpenZiti is moving to a new authentication model where this issue is handled differently (through revocations) that can be issued.

Closing due to end-of-life support for legacy authentication.
