### ISSUE TITLE
Ziti edge Posture check API TypeID values in swagger document needs to be updated

### ISSUE THREAD

**Issue by vinaynetfoundry** [openziti/ziti#1613]
Request:
POST https://{{controller-ip}}/edge/client/v1/posture-response
{
"id": "xxxxx",
"typeId": "postureResponseDomainCreate",
"domain": "test.com"
}

Response:
{
    "error": {
        "cause": {
            "code": "UNHANDLED",
            "message": "invalid typeId value: \"postureResponseDomainCreate\""
        },
        "code": "COULD_NOT_PARSE_BODY",
        "message": "The body of the request could not be parsed",
        "requestId": "JiwdN1jBFY"
    },
    "meta": {
        "apiEnrolmentVersion": "0.0.1",
        "apiVersion": "0.0.1"
    }
}

The API request fails if typeId(postureResponseDomainCreate, postureResponseMacAddressCreate etc..) specified in swagger document is used.

The API request succeeds if typeId is one of: DOMAIN, OS, MAC, PROCESS

**Comment by andrewpmartinez** [comment]
The OpenAPI documentation currently supports the full list of MFA types. They are:

      - OS
      - PROCESS
      - DOMAIN
      - MAC
      - MFA
      - PROCESS_MULTI
