### ISSUE TITLE
CA CRL/OCSP Support

### ISSUE THREAD

**Issue by andrewpmartinez** [openziti/ziti#1614]
Right now when a 3rd party CA is added to the Ziti Controller there is no way to stop any one certificate, that is correctly signed/dated/etc, that has been "revoked" (either actual revocation or should be blocked for some external reason.

Options for implementation:

- Add an internally managed Ziti revocation list
  - Easy but if there is a managed CRL/OCSP it becomes redundant
 - Add CRL/OCSP lookups for enrollment, periodical checks for new revocations, and ability to force revocation checks

**Comment by nenkoru** [comment]
Any news on this feature?

**Comment by andrewpmartinez** [comment]
This is now being tracked on the IDP/Security board here: https://github.com/orgs/openziti/projects/25 under this issue: https://github.com/openziti/ziti/issues/2092

It is slated for release this year (Oct/Nov).

**Comment by andrewpmartinez** [comment]
Closing as duplicate of https://github.com/openziti/ziti/issues/2092
