### ISSUE TITLE
Document REST API filtering and other shared semantics

### ISSUE THREAD

**Issue by andrewpmartinez** [openziti/ziti#1619]
This can be done in the Open API 2.0 documentation or a separate doc. 

> While you're on the subject of filters...
> I'd love some documentation.  I suspect they can do a lot more than the two use cases we use them for, and I had to trial and error my way through the syntax.  I'd love to be able to filter by updated date or other random properties of an entity... and/or semantics... operators other than equality... etc.

**Comment by ekoby** [comment]
done
