### ISSUE TITLE
Make binding for terminators required

### ISSUE THREAD

**Issue by andrewpmartinez** [openziti/ziti#1624]
Right now using the Edge API to create terminators, the `binding` attribute used to select the xgress component to provide egress is not required. If left blank, it will default to `transport`, which does not support e2e encryption.

Making it required forces the API client to decide what to define the binding is. Defaulting the value provides no positive feedback on what the system will do, and it is most likely the wrong value.

**Comment by ekoby** [comment]
paul said no longer an issue
