### ISSUE TITLE
Sessions are not removed if removed by fabric

### ISSUE THREAD

**Issue by andrewpmartinez** [openziti/ziti#1626]
*Experienced*
Having edge routers go down will remove active sessions that have no possible route at the fabric level. Querying for the sessions via the Edge API will still show the session active. Clients of that session will not know it is invalid when querying the Edge API.

*Expected*
If the fabric removes a session, that is reflected in the Ede API

*Reproduction*
1. Create a service w/ only 1 edge router that can handle it
1. Connect everything (edge router, sdk, controller)
1. Stop the edge router
1. Use `ziti-fabric list session` and `GET /sessions` to compare.

**Comment by smilindave26** [comment]
already addressed
