### ISSUE TITLE
ziti-tunnel tproxy: intercept locally generated packets without using local routes

### ISSUE THREAD

**Issue by scareything** [openziti/ziti#1635]
ziti-tunnel currently sets up a local route for the IP address of each intercepted service. The local route is being used to cause locally generated packets to traverse the PREROUTING iptables chain (where TPROXY can be applied), but there's another way to push local packets through PREROUTING:

1. create a custom routing table
2. add a default route to the custom table, sending all traffic to `dev lo`
3. add an ip rule that sends all packets marked "nf-intercept" to the custom routing table.
4. for each intercepted service, create an iptables rule on the OUTPUT chain marks any packets destined for the intercept ip:port:proto with the "nf-intercept" mark

**Comment by qrkourier** [comment]
Am I mistaken? I'm under the impression that `ziti router`'s tunnel mode `tproxy` does use iptables tproxy marks, not IP routes. If that's correct, then it's one of the distinguishing differences between `ziti-edge-tunnel`'s IP route approach, which requires elevated privs at the host level, and `ziti router` (and `ziti tunnel`) namespace'd approach with TPROXY, which happens to work in containers, and is therefore the only existing solution for pod-level transparent interception in Kubernetes.

For reference, I'm maintaining a comparison of the capabilities of both in this doc issue: https://github.com/openziti/ziti-doc/issues/383

**Comment by scareything** [comment]
Yes, local routes are necessary if locally generated packets need to be intercepted. The routes are not needed if the tunneler only intercepts packets that are received from other hosts (i.e. the tunneler is acting as a gateway).

The routes are needed because locally generated packets [would otherwise not traverse the mangle table or the PREROUTING chain](http://linux-ip.net/pages/diagrams.html), which is the [only place where the TPROXY iptables target is valid](https://www.man7.org/linux/man-pages/man8/iptables-extensions.8.html).

**Comment by qrkourier** [comment]
That makes sense and thank you for explaining it!

**Comment by smilindave26** [comment]
Closing per @scareything comment
