### ISSUE TITLE
verify JWKS endpoint when adding ext-jwt-signer

### ISSUE THREAD

**Issue by dovholuknf** [openziti/ziti#1681]
If the JWKS url has an invalid TLS configuration, the controller will never be able to connect/use the JWKS. This will manifest in the controller logs like this:
```
token signature is invalid: key is of invalid type ..... error during JWT parsing during API request
...
could not resolve jwks endpoint: Get \"https://--jwks-endpoint-here--\": tls: failed to verify certificate: x509: certificate signed by unknown authority","extJwtSignerId":"3BOLAaCcfeqvClefpiqLAt","extJwtSignerName":"browzer-keycloak-clint-ext-jwt-signer","file":"github.com/openziti/ziti/controller/model/authenticator_mod_ext_jwt.go:245","func":"github.com/openziti/ziti/controller/model.(*AuthModuleExtJwt).pubKeyLookup","issuer":"https://--jwks-endpoint-here--","kid":"Ss6jWw2SZ34ZlxtMWZR7TXqvUwx1lJNePmZTke9drdA","level":"error","method":"ext-jwt","msg":"error attempting to resolve extJwtSigner certificate used for signing
...
authorization failed, jwt did not verify
```

This error also manifests when simply adding the ext-jwt-signer with JWKS. Instead, creating the JWKS should __FAIL__ if the JWKS cannot be resolved, leaving behind no ext-jwt-signer.

If the TLS ever changes -- the ext-jwt-signer should be set to `Enabled         │ false` and a big scary message put into the logs telling me the ext-jwt-signer is disabled for "reason". also, toggling the signer back to enabled should also perform the validation

**Comment by qrkourier** [comment]
Is this issue now resolved that this related issue was closed?

https://github.com/openziti/ziti/issues/1690

**Comment by dovholuknf** [comment]
doesn't quite look like the same error to me?
