### ISSUE TITLE
CI: Outdated GitHub actions

### ISSUE THREAD

**Issue by mjtrangoni** [openziti/ziti#1745]
Hi,

Would you like to enable dependabot for this repo?

IMHO, at least for *github-actions* it would be a good enhancement. Otherwise, golang would possible as well, for updating the whole module vendoring.

If you agree, I can submit a PR for this.

Thank you!

**Comment by plorenz** [comment]
I wasn't aware you could setup dependabot for actions. I'd be happy to take a look at a PR :+1:
