### ISSUE TITLE
The run-router.sh file should check for an existing router

### ISSUE THREAD

**Issue by gberl002** [openziti/ziti#1746]
The exact process to replicate is not known for certain, however, here are what are believed to be the reproduction steps.

1. start router
1. stop router
1. rm persistent files
1. start router
fails (because router exists in openziti)

then:

1. deleted the router in openziti
1. start router
fails because enrollment was invalid, but the `access-control.init` file exists or something? (didn't really dig in)

then:

1. delete router in openziti
1. rm persistent files
1. start router
success

**Comment by smilindave26** [comment]
quickstart revamp obsolets
