### ISSUE TITLE
provide a better error when the user is not logged in

### ISSUE THREAD

**Issue by dovholuknf** [openziti/ziti#1772]
Running `ziti edge list ers` (or anything really) does not provide a CLEAR error to the user indicating they just aren't logged in. The feedback should be much more obvious than what is currently output.

See:
```
$ ziti edge list ers
error: no identity 'default' found in cli config /home/cd/.config/ziti/ziti-cli.json
```

☝️ not exactly obvious that they just haven't logged in yet...

**Comment by Vrashabh-Sontakke** [comment]
I would like to work on this issue.
The codebase is quite big, please help me find files related to this issue!

**Comment by plorenz** [comment]
> I would like to work on this issue. The codebase is quite big, please help me find files related to this issue!

That errors comes from here: https://github.com/openziti/ziti/blob/v1.0.0/ziti/util/identities.go#L328

A basic fix would maybe check the identity count and return an error saying you need to login if there are 0 saved logins. Above and beyond that, if the selected saved login isn't found you could output the list of saved logins and let the user know they could either login  or use `ziti edge use` to select an existing saved login.

**Comment by Vrashabh-Sontakke** [comment]
Thank you so much @plorenz for the jumpstart.
