### ISSUE TITLE
mgmt API accepts invalid address string

### ISSUE THREAD

**Issue by qrkourier** [openziti/ziti#1793]
An intercept.v1 config may specify an address, but a request to define an invalid address string like `hello.internal:80` should get bad request response, since the intercept address will never work. A valid address is an IPv4 or domain name.

**Comment by dovholuknf** [comment]
`hello.internal` works fine on windows. it's not 'invalid'. recommend to close the issue

**Comment by scareything** [comment]
intercept addresses are validated by the json schema using the [idn-hostname format](https://json-schema.org/draft/2020-12/json-schema-validation#name-hostnames). idn-hostname is surprisingly lenient, and in fact the address you've shown as an example _will_ work as a hostname:

```
$ grep hello /etc/hosts
5.5.5.5 hello.internal:80
$ ping hello.internal:80
PING hello.internal:80 (5.5.5.5) 56(84) bytes of data.
^C
```

**Comment by scareything** [comment]
fyi there's a [relevant comment](https://github.com/openziti/ziti/blob/release-next/tunnel/entities/intercept.v1.json#L18) in the intercept.v1 schema

**Comment by dovholuknf** [comment]
works as designed
