### ISSUE TITLE
change create router default to isTunnelerEnabled=True

### ISSUE THREAD

**Issue by qrkourier** [openziti/ziti#1852]
I often document or mention that a router must be created with `isTunnelerEnabled=True` to function in the way users typically expect.

Let's make this the default for `ziti edge create router`.

I'll send PR(s) to toggle the default based on the discussion on this issue.

**Comment by dovholuknf** [comment]
At this time, we'll be leaving it as is to make this a very explicit choice by the user to enable tunneling mode

**Comment by qrkourier** [comment]
What's the downside if the ER/T is opt-out? Seems more surprising that a router silently fails to function when a tunnel binding is configured and `isTunnelerEnabled=false` in the mgmt API.
