### ISSUE TITLE
ziti-edge-tunnel DNS resolver on LAN IP (rather than loopback)

### ISSUE THREAD

**Issue by damien-grau** [openziti/ziti#1856]
Hi, 

By default, ziti-edge-tunnel host a dns resolver on 127.0.0.53. Is there way to change this address to a LAN IP ?
In my case, i want to do this : 
![image](https://github.com/openziti/ziti/assets/100437527/273f2b33-f52c-4861-a163-3b7a18366b7d)

This is a very simplified illustration, we can imagine that devices on Network A are actually part of a larger private network, but in a segmented zone under a Tunneler, and this segmented part is linked to the Edge Router at the top of the Private Network.
So In this Private Network, we have 3 endpoints non-enrolled, I want to access the DNS resolver of the tunneler on its IP address (192.168.1.1) to resolve http.ziti for example but the dns resolver is on its loopback address. 

How can I put the tunneler's resolver on 192.168.1.1?
Should I use edge routers instead of tunnelers?

**Comment by qrkourier** [comment]
Hi @damien-grau! Here's a side-by-side comparison of `ziti-edge-tunnel run` vs. `ziti router run` capabilities, etc.: https://github.com/openziti/ziti-doc/issues/383

`ziti-edge-tunnel run` uses a configurable dynamic IP range and the built-in Ziti nameserver is always hosted on an IP in that range. The default range is 100.64/10 and the default nameserver address is 100.64.0.2.

The 127.0.0.53 IP you encountered is the default address of systemd-resolved's stub resolver, which is typically configured automatically by `ziti-edge-tunnel run` to send queries to the Ziti nameserver. You can inspect the configuration with `resolvectl`, e.g.,

```bash
❯ resolvectl dns ziti0
Link 2509 (ziti0): 100.64.0.2
```

**Comment by qrkourier** [comment]
You might be interested in the `--dns-ip-range` option if your goal is for the tunneler to use a different IP range, perhaps one that is already routable from some subnet.

```bash
❯ ziti-edge-tunnel run --help
ziti-edge-tunnel run: run Ziti tunnel (required superuser access)
usage: ziti-edge-tunnel run -i <id.file> [-r N] [-v N] [-d|--dns-ip-range N.N.N.N/n]

        -i|--identity <identity>        run with provided identity file (required)
        -I|--identity-dir <dir> load identities from provided directory
        -v|--verbose N  set log level, higher level -- more verbose (default 3)
        -r|--refresh N  set service polling interval in seconds (default 10)
        -d|--dns-ip-range <ip range>    specify CIDR block in which service DNS names are assigned in N.N.N.N/n format (default 100.64.0.1/10)
```

**Comment by scareything** [comment]
Let me try to clear up a couple of things. First, it probably isn't `ziti-edge-tunnel` that's responsible fort the socket that you see at 127.0.0.53:53. That is most likely the operating system's resolver - probably `systemd-resolved`. For example, on my fedora box:

```bash
$ sudo ss -nlpu src 127.0.0.53
State         Recv-Q        Send-Q                 Local Address:Port                 Peer Address:Port        Process        
UNCONN        0             0                      127.0.0.53%lo:53                        0.0.0.0:*            users:(("systemd-resolve",pid=724,fd=17))
```

And `ziti-edge-tunnel` configures its DNS server IP (100.64.0.2 by default) into the `systemd-resolved` resolver:
```bash
$ resolvectl status
Global
         Protocols: LLMNR=resolve -mDNS -DNSOverTLS DNSSEC=no/unsupported
  resolv.conf mode: stub
Current DNS Server: 127.0.0.1
       DNS Servers: 127.0.0.1

Link 2 (enp0s5)
    Current Scopes: DNS LLMNR/IPv4 LLMNR/IPv6
         Protocols: +DefaultRoute LLMNR=resolve -mDNS -DNSOverTLS DNSSEC=no/unsupported
Current DNS Server: fe80::f02f:4bff:fe80:d064
       DNS Servers: 10.211.55.2 fe80::f02f:4bff:fe80:d064

Link 14 (ziti0)
    Current Scopes: DNS
         Protocols: +DefaultRoute -LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
Current DNS Server: 100.64.0.2
       DNS Servers: 100.64.0.2
```

Are you looking to make `ziti-edge-tunnel's` dns server available to the other hosts that are behind it? This is different than exposing your host's resolver to the rest of the network.

**Comment by damien-grau** [comment]
Thanks for your replies !

Yes I want to expose the ziti-edge-tunnel's dns server to the other hosts behind it. I found a way with iptables to forward dns query at 192.168.1.100 (tunneler's IP) to the dns server on 100.64.0.2 : 
`iptables -t nat -A PREROUTING -s 192.168.1.0/24 -i enp0s3 -p udp --dport 53 -j DNAT --to 100.64.0.2`

I tried it on the edge-router above the tunneler and it worked : 
```
root@ziti-router:/home/ziti-router# dig @192.168.1.100 http.ziti

; <<>> DiG 9.18.18-0ubuntu0.22.04.1-Ubuntu <<>> @192.168.1.100 http.ziti
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 31662
;; flags: qr rd ad; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;http.ziti.			IN	A

;; ANSWER SECTION:
http.ziti.		60	IN	A	100.64.0.4

;; Query time: 4 msec
;; SERVER: 192.168.1.100#53(192.168.1.100) (UDP)
;; WHEN: Thu Mar 21 15:53:14 CET 2024
;; MSG SIZE  rcvd: 54
```

Is this a good way to do it like this?

**Comment by scareything** [comment]
Yes, an iptables rule on the ziti-edge-tunnel host is exactly what I was going to suggest!

**Comment by damien-grau** [comment]
Okay perfect!
I close this issue, thanks all.
