### ISSUE TITLE
enable Sprig functions for embedded Go templates

### ISSUE THREAD

**Issue by qrkourier** [openziti/ziti#1863]
Templating YAML is tedious and error prone, but we can make it less so by introducing the Sprig library (`github.com/Masterminds/sprig`).

For example, our embedded YAML templates currently have a meaningful number of space characters carefully placed to render with proper indentation. With Sprig, we can instead say "print this string at indentation level 2."

Before:

```go
// note the invisible two spaces preceding "listeners:"
{{ if .Router.IsPrivate }}#{{ end }}  listeners:
```
After:

```go
{{ if .Router.IsPrivate }}#{{ end }}{{- "listeners:" | nindent 2 }}
```

**Comment by dovholuknf** [comment]
personally, i don't see the need for another dependency for this. agree it's annoying but i'm fine with the annoyance to keep yet another dependency out of our code

**Comment by qrkourier** [comment]
I found another way to make the template slightly less error prone:

```go
{{- if and (not .Router.IsFabric) (eq .Router.TunnelerMode "tproxy") (.Router.Edge.LanInterface) }}
      lanIf: {{ .Router.Edge.LanInterface }}
{{- end }}
{{- if and (not .Router.IsFabric) (eq .Router.TunnelerMode "tproxy") (.Router.Edge.DnsSvcIpRange ) }}
      dnsSvcIpRange: {{ .Router.Edge.DnsSvcIpRange }}
{{- end }}
```

This way, the conditionally-rendered lines are left-justified, so indentation errors are more visible at a glance.

**Comment by qrkourier** [comment]
I'll revisit this if I have a specific need for Sprig functions.
