### ISSUE TITLE
Login Failed Unable to login to selected edge controller

### ISSUE THREAD

**Issue by guojinlong1** [openziti/ziti#1878]
I followed the link““ https://openziti.io/docs/learn/quickstarts/network/local-docker-compose ”I used Docker Compose to set up Ziti, but when I access ZAC, I don't know what username and password to use. When logging in with admin/admin, it shows “Login Failed Unable to login to selected edge controller”.
May I ask how to solve it？

**Comment by dovholuknf** [comment]
Sure enough that page doesn't talk about the password on it. It expects you to exec into the controller container and execute your ziti CLI functions but that isn't necessary. Inside that container an environment file was created that represents the set of answers used to install the overlay. 

you can get the password used when it started one a few ways:
Grep:
```
docker exec -it docker-ziti-controller-1 grep ZITI_PWD /persistent/ziti.env
if [[ "$ZITI_PWD" == "" ]]; then export ZITI_PWD="7vdTGwSykxWg8VClS1xJr5kTNXzyBI2C";
```
exec into the container and look at that file `/persistent/ziti.env`
or docker logs:
```
docker logs docker-ziti-controller-1 2>&1 | grep ZITI_PWD
Do you want to keep the generated admin password '7vdTGwSykxWg8VClS1xJr5kTNXzyBI2C'? (Y/n) INFO: using ZITI_PWD=7vdTGwSykxWg8VClS1xJr5kTNXzyBI2C
NOT OVERRIDING: env var ZITI_PWD already set. using existing value
ZITI_PWD overridden: 7vdTGwSykxWg8VClS1xJr5kTNXzyBI2C
```

Alternatively when you start the container you can set that ZITI_PWD and it'll use whatever you set it as the initial password:
```
ZITI_PWD=here_is_my_password docker compose --project-name docker up
```
Then when you grep the logs you'll see:
```
$ docker logs docker-ziti-controller-1 2>&1 | grep ZITI_PWD
ZITI_PWD overridden: here_is_my_password
```

I'll close this issue as complete but if you need to reopen it please do. Also we tend to use discourse for "how-to" and "help" related issues. You can find that here: https://openziti.discourse.group/

cheers
