### ISSUE TITLE
grc4ciso

### ISSUE THREAD

**Issue by grcbit** [openziti/ziti#1885]
Project Name: grc4ciso
Link to project site: https://grc4ciso.com
How OpenZiti is used or why OpenZiti was chosen: grc4ciso is a SaaS platform that unifies the functionalities of a XDR + GRC + ZeroTrust. Zero Trust is based on OpenZiti, providing overlay network components necessary to integrate zero trust into small and medium-sized companies.
Link to logo: https://grc4ciso.com/assets/img/logo_1.png

**Comment by dovholuknf** [comment]
closed by #1886
