### ISSUE TITLE
Raft should not initialize if db is misconfigured

### ISSUE THREAD

**Issue by plorenz** [openziti/ziti#1973]
Controller will try to initialize raft from the DB if it's configured. If it's configured but pointing to an invalid location, the controller will panic, but raft will already be initialized. The second run will then succeed. It should fail consistently, before raft is initialized.

**Comment by Vrashabh-Sontakke** [comment]
Hi @plorenz, I would like to work on this issue.

Please help me know whether I am on the correct path :

https://github.com/openziti/ziti/blob/a998a4afaf166e912f1cd60fee9773eb7939a3b8/controller/controller.go#L518C1-L587C1

**Comment by Vrashabh-Sontakke** [comment]
@plorenz , no problem, I would love to see your code (pr) and learn from it. 
I like to tackle issues with easy-medium level of difficulty, will surely post on discourse.
