### ISSUE TITLE
Implement subscriber model for identity/service events in router

### ISSUE THREAD

**Issue by plorenz** [openziti/ziti#1990]
Add enough information to the router data model so that we can provide service lists and change notifications for services in the router. This information can be used internally by ER/T or can be distributed to SDKs. 

* Add service config override mappings to identity
* Add configs to services
* Add configs to RDM or allow them to be retrieved/invalidated by the router
* Implement subscriber API

**Comment by qrkourier** [comment]
Oooh, nice.
