### ISSUE TITLE
add CITATION.cff

### ISSUE THREAD

**Issue by ruzko** [openziti/ziti#1998]
I'm writing [a thesis](https://gitlab.com/papiris/ml-predator-control-thesis) wherein ziti is used, and I'd like to properly cite / give credit.
I couldn't find any appropriate documentation about how you'd like this done.

Could you add a [CITATION.cff](https://citation-file-format.github.io/) file to this repo? :nerd_face:

**Comment by dovholuknf** [comment]
Thanks for asking! As you can tell, we're unfamiliar with the citation file format at this time. I'm trying to do some research on the matter. 

Is this the only repo you'd reference? I believe you were using python too -- would you want a .cff there as well?

I am trying to learn if/how dependencies are referenced, trying to watch a few videos to learn, etc. in the meantime.

**Comment by ruzko** [comment]
Thanks for being so quick on the ball :)

I could of course reference the py SDK as well, if you'd like that.
Re: how dependencies should be referenced, I'd be delighted if you could share your findings as well; as I'm pretty fresh on the subject too :book: 
I'm mostly going with my gut feeling for now, in a "credit goes where credit's due" kinda way. Citing all direct dependencies, as well as the most vital indirect dependencies.

Here are a few of the other dependencies I'll cite, which have CITATION.cff or similar:
https://github.com/abhiTronix/deffcode

https://github.com/tiangolo/sqlmodel

https://github.com/ultralytics/ultralytics
