### ISSUE TITLE
write a test for autoca enrollment

### ISSUE THREAD

**Issue by qrkourier** [openziti/ziti#2033]
Everything is tested already except `ziti edge enroll` using the auto-create method (`autoca`) which negotiates client TLS to and requests `/edge/client/v1/enroll?method=ca`.

**Comment by andrewpmartinez** [comment]
By "everything is tested" that is the REST API presentation and its implementation.

**Comment by smilindave26** [comment]
REST API tests are done.  @qrkourier - create new issue for CLI if needed
