### ISSUE TITLE
Edge Routers list for edge sessions should be sorted by online status first

### ISSUE THREAD

**Issue by mikegorman-nf** [openziti/ziti#2046]
When creating an Edge Session, the system currently sorts the Edge Routers by id, and limits the overall list to 10.  This can create a situation where online routers are excluded and offline routers are in the session "slots".  The list should be sorted first by online status, to give the identity the most robust operational state.

**Comment by plorenz** [comment]
Also bumping the limit for the number of returned routers to 25.

**Comment by plorenz** [comment]
Adding `connected` symbol to the router store and `connected` and `online` symbols to the edge router store.
