### ISSUE TITLE
Add db compact ability to ziti-controller command

### ISSUE THREAD

**Issue by andrewpmartinez** [openziti/ziti#213]
bbolt supports a `compact` command that can be used to reduce the size of databases. This can also be done via the Edge API w/ a database snapshot, but this is a very easy way for a sysadmin to do the same thing.

**Comment by andrewpmartinez** [comment]
The compact logic isn't exposed. Seeing if we can bolt to expose it here: https://github.com/etcd-io/bbolt/issues/247 . I put a PR up for them as well.

If not we can always copy it...

**Comment by ekoby** [comment]
done
