### ISSUE TITLE
cached data model file set to

### ISSUE THREAD

**Issue by cltgit** [openziti/ziti#2195]
Hello, I am showing the following error when starting the public route, I have not seen this error in the previous version.
How can I solve this problem so that the public route starts smoothly
![image](https://github.com/openziti/ziti/assets/20314793/85c63a73-e83d-40e2-93ac-c8562ec4480c)

router/internal/edgerouter/config.go:154
func:github.com/openziti/ziti/router/internal/edgerouter.(*Config).LoadConfigFromMap
level:info
msg:cached data model file set to: /home/work/projec/related/www.router.com/www.router.com.yaml.json.gzip
time:2024-07-03T09:13:24.195Z

error:open  /home/work/projec/related/www.router.com/www.router.com.yaml.json.gzip: no such file or directory
/router/state/manager.go:176
func:github.com/openziti/ziti/router/state.(*ManagerImpl).LoadRouterModel
level:error
msg:could not load router model from file [ /home/work/projec/related/www.router.com/www.router.com.yaml.json.gzip]
time:2024-07-03T09:13:24.196Z

**Comment by plorenz** [comment]
Hi, just to clarify: is the router successfully starting? Or is the router stopping after this error? 

You are correct that in most cases this message should not be an error, so we're going to fix that, but want to be sure that your router is still starting successfully after the error message pops up.
