### ISSUE TITLE
Emit an event when hasEdgeRouterConnection state changes for an Identity

### ISSUE THREAD

**Issue by tburtchell** [openziti/ziti#2234]
It would be great to know when an identity connects to an edge router so that I can report it in our monitoring console.  Today I have to poll for this information, which does not scale well.

**Comment by plorenz** [comment]
There's another issue: https://github.com/openziti/ziti/issues/1835 which may be related. Could we use the same mechanism (connected events) for edge connections to routers? 

So events would be something like:

* type: [router-to-ctrl|ctrl-to-ctrl|edge-to-ctrl|edge-to-router]
* Identity (router/identity/controller id)
* timestamp
* Source IP Address

Would that work to cover the use case you're envisioning?
