### ISSUE TITLE
router deployments - start supporting --private flag 

### ISSUE THREAD

**Issue by qrkourier** [openziti/ziti#2275]
Add a bootstrapping var `ZITI_ROUTER_PRIVATE`  which sends `ziti create config router edge --private` when "true"

**Comment by dovholuknf** [comment]
What if we simply allow a string to be supplied that's added to the config comand instead so that people can override more than just this?

**Comment by qrkourier** [comment]
Like `ZITI_ROUTER_BOOTSTRAP_CONFIG_ARGS`?
