### ISSUE TITLE
Unable to start controller due to trust domain issue after upgrading (deb install)

### ISSUE THREAD

**Issue by nickchen120235** [openziti/ziti#2321]
Hi! I'm trying openziti inside my VyOS (debian-based OS for router) virtual machine, with controller and edge router installed along side.

After upgrading to 1.1.7 (previous version 1.1.4) via `apt` I cannot start ziti-controller.

`journalctl -xeu ziti-controller` shows nothing
```
Aug 13 08:34:52 vyos systemd[1]: Starting ziti-controller.service - OpenZiti Controller...
░░ Subject: A start job for unit ziti-controller.service has begun execution
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ A start job for unit ziti-controller.service has begun execution.
░░ 
░░ The job identifier is 64171.
Aug 13 08:34:52 vyos entrypoint.bash[26522]: WARN: set VERBOSE=1 or DEBUG=1 for more output
Aug 13 08:34:52 vyos systemd[1]: ziti-controller.service: Control process exited, code=exited, status=1/FAILURE
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ An ExecStartPre= process belonging to unit ziti-controller.service has exited.
░░ 
░░ The process' exit code is 'exited' and its exit status is 1.
Aug 13 08:34:52 vyos systemd[1]: ziti-controller.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ The unit ziti-controller.service has entered the 'failed' state with result 'exit-code'.
Aug 13 08:34:52 vyos systemd[1]: Failed to start ziti-controller.service - OpenZiti Controller.
░░ Subject: A start job for unit ziti-controller.service has failed
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ A start job for unit ziti-controller.service has finished with a failure.
░░ 
░░ The job identifier is 64171 and the job result is failed.
```
If I try to start it from command line (in `/var/lib/ziti-controller` folder), it died with the following output

```
root@vyos:/var/lib/ziti-controller# ziti controller run ./config.yml 
panic: could not generate default trust domain: error generating default trust domain from root CA: no root CA detected after chain assembly from the root identity server cert and ca bundle

goroutine 1 [running]:
github.com/openziti/ziti/controller/config.LoadConfig({0x7ffc276880ec?, 0xc0008078c0?})
	github.com/openziti/ziti/controller/config/config.go:383 +0x3445
github.com/openziti/ziti/ziti/controller.run(0xc000beee00?, {0xc000be82f0, 0x1, 0x3a65226?})
	github.com/openziti/ziti/ziti/controller/run.go:54 +0x54a
github.com/spf13/cobra.(*Command).execute(0xc000a89508, {0xc000be82c0, 0x1, 0x1})
	github.com/spf13/cobra@v1.8.1/command.go:989 +0xab1
github.com/spf13/cobra.(*Command).ExecuteC(0x5a7f5c0)
	github.com/spf13/cobra@v1.8.1/command.go:1117 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.8.1/command.go:1041
github.com/openziti/ziti/ziti/cmd.Execute()
	github.com/openziti/ziti/ziti/cmd/cmd.go:81 +0x1a
main.main()
	github.com/openziti/ziti/ziti/main.go:51 +0xf
```

When searching for possible solutions, I found [this post](https://openziti.discourse.group/t/attempting-to-use-ziti-controller-helm-chart-panic-could-not-generate-default-trust-domain/2932) which has similar issue. Mine isn't a HA setup but I do notice [the incompatibility mentioned here](https://openziti.discourse.group/t/attempting-to-use-ziti-controller-helm-chart-panic-could-not-generate-default-trust-domain/2932/3).

Also that post mentioned intermediate versions 1.1.5 and 1.1.6 but `apt-cache policy openziti` only shows
```
root@vyos:/var/lib/ziti-controller# apt-cache policy openziti
openziti:
  Installed: 1.1.7
  Candidate: 1.1.7
  Version table:
 *** 1.1.7 500
        500 https://packages.openziti.org/zitipax-openziti-deb-stable debian/main amd64 Packages
        100 /var/lib/dpkg/status
     1.1.4 500
        500 https://packages.openziti.org/zitipax-openziti-deb-stable debian/main amd64 Packages
     1.1.2 500
        500 https://packages.openziti.org/zitipax-openziti-deb-stable debian/main amd64 Packages
(and some older versions)
```

I can start the controller after downgrading to 1.1.4 so I guess maybe we missed some intermediate versions on apt or did I mess up something?

**Comment by nickchen120235** [comment]
New installation seems to be fine. Only upgrading is affected during my testing.

**Comment by dovholuknf** [comment]
Hi @nickchen120235, thank you for helping to narrow down this is an issue with upgrading. We'll have a look.

**Comment by andrewpmartinez** [comment]
The error message you are seeing is because of the introduction of trust domains: https://github.com/openziti/ziti/blob/main/CHANGELOG.md#trust-domain-configuration

Since you are upgrading and do not have a trust domain specified in your configuration, the controller is trying to generate one deterministically from your PKI's root CA. This is done by building a chain from the controller client cert back up to a root using the CA bundle and the signer cert's CA bundle.

You can avoid this by simply defining the trust domain according to the change log linked above, but I'd be more concerned that a chain back to the root could not be created. It makes me think that the instance has a misconfigured PKI.

If you want, you can carefully provide the public certificates from your controller's root `identity.server_cert` `identity.cert_ and `identityl.ca` fields as well as the `edge.api.signingCert.cert` and `edge.api.signingCert.ca`.

**Comment by qrkourier** [comment]
I've associated the pull requests I sent to address this issue.

**Comment by qrkourier** [comment]
@nickchen120235  You installed the Linux controller package `openziti-controller` which I discovered too late can not be upgraded >=1.1.6. The simplest fix is to add the following to `/var/lib/private/ziti-controller/config.yml`:

```yaml
trustDomain: spiffe://ziti.example.com
```

The practical reason your controller failed to start is that your controller's default `identity.cert` was erroneously saved as a leaf only, i.e., `/var/lib/private/ziti-controller/pki/intermediate/certs/client.cert`. That file must be a chain for the "generate one deterministically from your PKI's root CA" fallback behavior to succeed.

The `trustDomain` directive has higher precedence than generating one from the root cert's SHA1, so setting `trustDomain` will avoid the panic you encountered.

Alternatively, you may concatenate the intermediate cert to your existing client.cert leaf file. This will allow the controller to start by completing the client cert chain even without the new `trustDomain` config directive.

As we move towards controller clustering, it's sufficient for now to pick a permanent trust domain for your solo controller. This can be the FQDN of the controller.

**Comment by nickchen120235** [comment]
Thanks for the replies

> Additionally, how was the PKI for this instance generated? If it was generated by ziti tooling, what version was it generated with? It might be an issue with the quickstart's configuration or the `ziti pki` tooling.

I've never used `ziti pki` command before so I guess I'm using the default generated one?

> If you want, you can carefully provide the public certificates from your controller's root `identity.server_cert` `identity.cert` and `identityl.ca` fields as well as the `edge.api.signingCert.cert` and `edge.api.signingCert.ca`.

Where can I find these files?

In the meantime I'll try the simple fix as this won't be a long-term deployment for me.

**Comment by nickchen120235** [comment]
After applying the fix and upgrading, I can now start the controller via command line. However, starting the controller with systemd fails because `entrypoint.bash` in ExecStartPre` fails. There was no pre-flight check in the service file of the old version.

If I execute the pre-flight script with `DEBUG=1 /opt/openziti/etc/controller/entrypoint.bash check config.yml` (inside `/var/lib/ziti-controller`), the output is
```
root@vyos:/var/lib/ziti-controller# DEBUG=1 /opt/openziti/etc/controller/entrypoint.bash check config.yml
+ ((  2  ))
+ [[ check == run ]]
+ source /opt/openziti/etc/controller/bootstrap.bash
++ : 1
++ : 1
++ ((  DEBUG  ))
++ exec
++ set -o xtrace
++ trap exitHandler EXIT SIGINT SIGTERM
++ : pki
++ : root
++ : intermediate
++ : server
++ : client
++ : ctrl
++ : bbolt.db
++ : 0.0.0.0
+++ mktemp
++ : /tmp/tmp.QeZeKSAfYO
++ [[ /opt/openziti/etc/controller/bootstrap.bash == \/\o\p\t\/\o\p\e\n\z\i\t\i\/\e\t\c\/\c\o\n\t\r\o\l\l\e\r\/\e\n\t\r\y\p\o\i\n\t\.\b\a\s\h ]]
+ [[ '' == true ]]
+ [[ check =~ check ]]
+ [[ ! -s config.yml ]]
++ dbFile config.yml
++ ((  1  ))
++ local _config_file=config.yml
++ awk -F: '/^db:/ {print $2}' config.yml
++ xargs realpath
+ [[ ! -w /var/lib/private/ziti-controller/bbolt.db ]]
+ [[ '' == true ]]
+ exit
+ exitHandler
+ echo 'WARN: set VERBOSE=1 or DEBUG=1 for more output'
WARN: set VERBOSE=1 or DEBUG=1 for more output
+ [[ -s '' ]]
+ [[ -s '' ]]
root@vyos:/var/lib/ziti-controller#
```

**Comment by qrkourier** [comment]
This is likely a different result than when it's run by systemd because the service unit also loads `/opt/openziti/etc/controller/service.env`.

What is the log output that indicated to you that "starting the controller with systemd fails?"

**Comment by qrkourier** [comment]
> I've never used ziti pki command before so I guess I'm using the default generated one?

Yes, the Linux package uses the `ziti pki` command to generate the controller's PKI. Since v1.1.8, the PKI is created when the administrator executes `sudo /opt/openziti/etc/controller/bootstrap.bash` after installing the package. Prior to v1.1.8, the PKI was created the first time the service started.

> Where can I find these files?

All PKI-related files created by the Linux package are found in `/var/lib/private/ziti-controller/pki`. Here's how you'd concatenate the client leaf and its intermediate cert to allow the controller to start without a `trustDomain` directive in config.yml.

```bash
sudo cat /var/lib/ziti-controller/pki/intermediate/certs/intermediate.chain.pem | sudo tee -a /var/lib/ziti-controller/pki/intermediate/certs/client.cert 
```

**Comment by nickchen120235** [comment]
> What is the log output that indicated to you that "starting the controller with systemd fails?"

`journalctl -xeu ziti-controller` only shows
```
Aug 14 00:28:01 vyos systemd[1]: Starting ziti-controller.service - OpenZiti Controller...
░░ Subject: A start job for unit ziti-controller.service has begun execution
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ A start job for unit ziti-controller.service has begun execution.
░░ 
░░ The job identifier is 4936.
Aug 14 00:28:01 vyos entrypoint.bash[3263]: WARN: set VERBOSE=1 or DEBUG=1 for more output
Aug 14 00:28:01 vyos systemd[1]: ziti-controller.service: Control process exited, code=exited, status=1/FAILURE
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ An ExecStartPre= process belonging to unit ziti-controller.service has exited.
░░ 
░░ The process' exit code is 'exited' and its exit status is 1.
Aug 14 00:28:01 vyos systemd[1]: ziti-controller.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ The unit ziti-controller.service has entered the 'failed' state with result 'exit-code'.
Aug 14 00:28:01 vyos systemd[1]: Failed to start ziti-controller.service - OpenZiti Controller.
░░ Subject: A start job for unit ziti-controller.service has failed
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ A start job for unit ziti-controller.service has finished with a failure.
░░ 
░░ The job identifier is 4936 and the job result is failed.
```
`systemctl status ziti-controller` shows
```
root@vyos:~# systemctl status ziti-controller
● ziti-controller.service - OpenZiti Controller
     Loaded: loaded (/lib/systemd/system/ziti-controller.service; enabled; preset: enabled)
    Drop-In: /etc/systemd/system/ziti-controller.service.d
             └─override.conf
     Active: activating (auto-restart) (Result: exit-code) since Wed 2024-08-14 00:30:04 UTC; 28ms ago
    Process: 4188 ExecStartPre=/opt/openziti/etc/controller/entrypoint.bash check config.yml (code=exited, status=1/FAILURE)
        CPU: 7ms
```
The service files are remain untouched since installation.

My `/opt/openziti/etc/controller/service.env`
```
# set "false" to disable bootstrapping
ZITI_BOOTSTRAP=false
# create a new PKI unless it exists
ZITI_BOOTSTRAP_PKI=true
# create a config file unless it exists if "true", set "force" to overwrite (changing the advertised URI will break
# existing enrollments who will be unable to connect to the controller)
ZITI_BOOTSTRAP_CONFIG=true
# create a new database unless it exists
ZITI_BOOTSTRAP_DATABASE=true
# BASH script that defines function bootstrap()
ZITI_CTRL_BOOTSTRAP_BASH=/opt/openziti/etc/controller/bootstrap.bash
# renew server and client certificates every startup
ZITI_AUTO_RENEW_CERTS=true

ZITI_ARGS='--'
```

I remember adding `ZITI_ARGS` manually because when I first upgraded I could pass the pre-flight check but `ziti` cli is complaining about too many arguments when starting the controller with systemd.

**Comment by qrkourier** [comment]
Thank you for confirming the log output and your env vars. 

I suspect a bug in the entrypoint script failing to handle `ZITI_BOOTSTRAP=false`. 

The expected result is non error exit code 0 and run ExecStart normally, but it appears to exit non-0 and abort the service. 😔

I will diagnose when I'm at the keyboard in a few hours and add a test case and bugfix for this. I think it will be changing L49 of entrypoint.bash to `exit 0`. 

You also mentioned the too many arguments error. Please try replacing the `--` placeholder like this. 

```bash
ZITI_ARGS='--verbose’
```
