### ISSUE TITLE
Add verify-network / verify-traffic

### ISSUE THREAD

**Issue by dovholuknf** [openziti/ziti#2357]
Users are constantly configuring their overlay incorrectly because it's not always easy to understand how to configure the overlay when first starting out. this leads to numerous discourse posts for straightforward issues.

Add two commands to help new users:
* verify-network - this command will look at config files for obvious flaws
* verify-traffic - this command will send actual traffic over the overlay and ensure it's setup properly

**Comment by qrkourier** [comment]
relevant resource: https://cuelang.org/docs/concept/how-cue-enables-data-validation/
