### ISSUE TITLE
ziti fabric add-identity commands cannot in 004-controller-pki.md

### ISSUE THREAD

**Issue by KerwinKoo** [openziti/ziti#2388]
I notice that "Remove ziti fabric add/remove-identity commands" in #1921 , but not changed in [doc/004-controller-pki.md](https://github.com/openziti/ziti/blob/main/doc/004-controller-pki.md):

```
ziti fabric add-identity \
    --cli-identity "${ZITI_NETWORK} Management" \
    --ca-cert ${ZITI_PKI}/${ZITI_CA_NAME}/certs/${ZITI_NETWORK}.cert \
    --client-cert ${ZITI_PKI}/${ZITI_CA_NAME}/certs/${ZITI_NETWORK}-dotzeet.cert \
    --client-key ${ZITI_PKI}/${ZITI_CA_NAME}/keys/${ZITI_NETWORK}-dotzeet.key
```
Which commands can be used instead of `ziti fabric add-identity` in the aforementioned code snippet? It would be greatly thanks if the file 004-controller-pki.md could be updated accordingly!

Thanks very much!

**Comment by qrkourier** [comment]
Hi @KerwinKoo! You found the developer docs for people contributing to OpenZiti. It's true; they're a bit stale. There are several "quickstart" options for running a temporary, local stack of Ziti that are less manual and may be appropriate if your aims include implementing a Ziti SDK or learning the ops concepts: https://openziti.io/docs/category/network

If you happen to be looking for long-lived, production deployments, then check out these guides: https://openziti.io/docs/category/deployments

**Comment by KerwinKoo** [comment]
@qrkourier Thank you for your response. I am hoping to understand each environment variable, PKI, and module of Ziti through manual deployment, all the way to understanding the overall structure. I have also read several guides and am concerned that the automatic deployment method might miss some details.
It seems that expressInstall is still the most comprehensive option.
Thanks again.
