### ISSUE TITLE
Identity cert/key reloading doesn't work in Linux, but work in Windows

### ISSUE THREAD

**Issue by andrewpmartinez** [openziti/ziti#2473]
*Experienced*

Updating a certificate or key file for any identity section does not reload cert/keys in Linux. Does in Windows.

*Expected*

Equivalent behavior as to Windows.

*Reproduction*
1. Run a controller in Linux
2. Run `touch` on the controller cert/key
3. Note the lack of logging about reloading

**Comment by qrkourier** [comment]
I need to verify this will works with Linux files for which `$ mountpoint FILE` evaluates true, which is a factor for deployment environments where configuration files are typically projected into a container.

**Comment by andrewpmartinez** [comment]
> I need to verify this will works with Linux files for which `$ mountpoint FILE` evaluates true, which is a factor for deployment environments where configuration files are typically projected into a container.

You can verify that functionality separately from this PR.
