### ISSUE TITLE
JWT signer secondary auth: not enough information to continue

### ISSUE THREAD

**Issue by ekoby** [openziti/ziti#2478]
if I set up an auth policy with JWT signer as secondary auth and authenticate with key/cert I get an api session (irrelevant field removed):
```
  "authQueries": [
    {
      "provider": "url",
      "typeId": "EXT-JWT"
    }
  ],
  "identityId": "JTR.7wXlT",

  "isMfaComplete": false,
  "isMfaRequired": false
}
```

1. `authQueries` does not give enough information to start OIDC authentication (url, clientId, claim, audience are needed) 
     maybe external signer id/name would be enough to do a lookup
1. should `isMfaRequired` be set? I think that's the case with TOTP secondary

**Comment by andrewpmartinez** [comment]
This was confirmed to be an issue in legacy authentication.
