### ISSUE TITLE
local cannot access：https://ziti-edge-controller:1280

### ISSUE THREAD

**Issue by yolk23321** [openziti/ziti#2487]
I successfully deployed using the local Docker Compose method and added the mapping `<local IP> ziti-edge-controller` to the local hosts file. However, the browser cannot access `https://ziti-edge-controller:1280`, but it can access `https://localhost:1280`. This is likely an SSL certificate issue, right? Will this affect my future operations? Can you provide a solution?

<img width="1657" alt="image" src="https://github.com/user-attachments/assets/0e5d9da5-063e-46ab-b141-0c4f3cd8ec4c">

<img width="405" alt="image" src="https://github.com/user-attachments/assets/64cabed3-4bb5-4101-aede-8d887ddca3a3">

**Comment by yolk23321** [comment]
Also, I have a problem that keeps prompting Session Expired when I log in to ZAC

**Comment by dovholuknf** [comment]
Support requests are best handled through our Discourse forum. Would you mind opening a dialog there? More people see it and you'll get faster help. It'll be best if you open two separate issues as well, the ZAC is maintained by a different people.

https://openziti.discourse.group/

> This is likely an SSL certificate issue, right? Will this affect my future operations? 

Yes it will affect future operations. You need to get this right, right from the start.  Would you mind if we continue this on discourse?

**Comment by yolk23321** [comment]
ok

**Comment by yolk23321** [comment]
> I successfully deployed using the local Docker Compose method and added the mapping `<local IP> ziti-edge-controller` to the local hosts file. However, the browser cannot access `https://ziti-edge-controller:1280`, but it can access `https://localhost:1280`. This is likely an SSL certificate issue, right? Will this affect my future operations? Can you provide a solution?

https://openziti.discourse.group/t/zac-login-always-prompts-that-the-session-has-expired/3267

**Comment by yolk23321** [comment]
> I successfully deployed using the local Docker Compose method and added the mapping `<local IP> ziti-edge-controller` to the local hosts file. However, the browser cannot access `https://ziti-edge-controller:1280`, but it can access `https://localhost:1280`. This is likely an SSL certificate issue, right? Will this affect my future operations? Can you provide a solution?
> 
> <img alt="image" width="1657" src="https://private-user-images.githubusercontent.com/173050151/377463922-0e5d9da5-063e-46ab-b141-0c4f3cd8ec4c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxNjkxNDgsIm5iZiI6MTcyOTE2ODg0OCwicGF0aCI6Ii8xNzMwNTAxNTEvMzc3NDYzOTIyLTBlNWQ5ZGE1LTA2M2UtNDZhYi1iMTQxLTBjNGYzY2Q4ZWM0Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxN1QxMjQwNDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNTI3NDdjYTA0NjA1NTZiYmYzZWE4NTRkOTljNmM0NThhODM0NjQ5YzYzM2Y4MTBmYWE0OWY4ZjA5MTI0MWIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.HAnLjz4DTL9lriutI4extF_SQOss8-wV2jar9PScRC8"> <img alt="image" width="405" src="https://private-user-images.githubusercontent.com/173050151/377464105-64cabed3-4bb5-4101-aede-8d887ddca3a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxNjkxNDgsIm5iZiI6MTcyOTE2ODg0OCwicGF0aCI6Ii8xNzMwNTAxNTEvMzc3NDY0MTA1LTY0Y2FiZWQzLTRiYjUtNDEwMS1hZWRlLThkODg3ZGRjYTNhMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxN1QxMjQwNDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZjUxNmQyYmFlMzMyMWM2MGQxN2IzOGI4NDMzODBmOGFkMjA1Njk5M2MxYzJlNTkxOWYzODRkNTUxODcxNGIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.bWP3hfYPSi9gphCouo3edpQ1L6WbsHmHVeePI6ao5GE">

https://openziti.discourse.group/t/local-cannot-access-https-ziti-edge-controller-1280/3266

**Comment by dovholuknf** [comment]
closing. thanks!

- https://openziti.discourse.group/t/local-cannot-access-https-ziti-edge-controller-1280/3266
- https://openziti.discourse.group/t/zac-login-always-prompts-that-the-session-has-expired/3267
