### ISSUE TITLE
fix router CSR loading

### ISSUE THREAD

**Issue by andrewpmartinez** [openziti/ziti#2491]
*Experienced*

CSR definitions moved to the root for enrollment, but when running the router, it still requires the `edge.csr` definition if `edge` is defined.

*Expected*

Whether enrolling or running a router, it should check the root `csr` path first and the `edge.csr` (if `edge` is defined). It should error if neither is provided. It should succeed where the root `csr` is provided or both are provided (preferring the root definition)

*Reproduction*

Create a router config using the root `csr` definition and enroll it. Then run it.

**Comment by qrkourier** [comment]
:sewing_needle: https://github.com/openziti/ziti-doc/issues/951
