### ISSUE TITLE
Ziti ID with leading hyphen causes command-line parameter ambiguity

### ISSUE THREAD

**Issue by qrkourier** [openziti/ziti#2534]
A Ziti ID with a leading hyphen creates difficulty for CLI users. I can work around this with `ziti` and `zrok` CLI in a POSIX shell by separating flags from positionals, e.g., `ziti edge delete enrollment -- '-zM681AVqN'` or  `zrok admin create frontend -- -D3xLHGw2 public https://{token}.zrok.example.com` , but this is a somewhat obscure solution that many users will not discover readily.

Workarounds Powershell/Command shells on Windows do exist, but seem even more obscure IMO. There's a `--%` operator that terminates the PowerShell interpreter, and it's possible to wrap a CLI with a cmdlet with strict parameter parsing.

**Comment by dovholuknf** [comment]
i don't know what you're talking about, you just quote it in powershell?

```
ziti edge list identities 'id contains "-"'
```

i recommend we close this issue

**Comment by emoscardini** [comment]
I agree, it's a pain when the id's start with a leading hyphen & not everyone knows the workaround.   This issues makes working with those ids frustrating.

**Comment by plorenz** [comment]
Circuits already cycle ids until they get one that starts with an alphanumberic. We could probably switch to that for all ids.
