### ISSUE TITLE
Create Config Controller Commands Are Incorrect

### ISSUE THREAD

**Issue by bonedaddy** [openziti/ziti#306]
I installed `ziti` locally, and attempting to follow the CLI commands given in the help menu to create the controller config do not work as per the following output:

```
$  ziti create config controller --ctrlListener quic:0.0.0.0:6262
Error: unknown flag: --ctrlListener
Usage:
  ziti create config controller [flags]

Aliases:
  controller, ctrl

Examples:
  # Create the controller config
  ziti create config controller
  
  # Create the controller config with a particular ctrlListener
  ziti create config controller -ctrlListener quic:0.0.0.0:6262

Flags:
  -b, --batch-mode              In batch mode the command never prompts for user input
  -i, --configIdentity string   Which configIdentity to use
  -h, --help                    help for controller
      --staging                 Install/Upgrade components from the ziti-staging repo
  -t, --timeout int             Timeout for REST operations (specified in seconds) (default 5)
      --verbose                 Enable verbose logging


unknown flag: --ctrlListener
```

**Comment by dovholuknf** [comment]
The ziti cli tool has gone through some iterations. That command might be out of date. 

There are some example config files you can look at in the /etc folder that can help. There's also some scripts in quickstart/local that help get you started too. I run the init.sh script in there routinely to bootstrap my local dev environment.

Happy to continue the dialog with you to get you up and running.
