### ISSUE TITLE
[enhancement] show upgrade message

### ISSUE THREAD

**Issue by qrkourier** [openziti/ziti#541]
It would be helpful for the `ziti-tunnel` CLI to print a warning message to stderr when an upgrade for the same CPU architecture is available. Here's an example of the message printed by the kOps CLI.

```bash
*********************************************************************************

A new kops version is available: 1.21.2
Upgrading is recommended
More information: https://github.com/kubernetes/kops/blob/master/permalinks/upgrade_kops.md#1.21.2

*********************************************************************************
```

**Comment by qrkourier** [comment]
@dovholuknf @plorenz I'd be interested in contributing this if you are able to give me some direction and coaching.

**Comment by plorenz** [comment]
> @dovholuknf @plorenz I'd be interested in contributing this if you are able to give me some direction and coaching.

Sure, seems like a nice, user-friendly feature :+1:

**Comment by qrkourier** [comment]
This was done.
