### ISSUE TITLE
allow routers to be re-enrolled

### ISSUE THREAD

**Issue by dovholuknf** [openziti/ziti#561]
in the rare case when a router goes offline and the certificate was not able to be reenrolled before the restart, the router will not be able to reenroll because it cannot connect to the controller.

Another scenario where this is useful is to migrate the entire machine from one OS to another or one region to another etc

**Comment by qrkourier** [comment]
That first scenario describes an expiration of the router's user cert it'd use to authenticate to one of the controller's APIs, correct? I take it that an authenticated router is therefore able to request and install a fresh user certificate automatically with today's latest release?

**Comment by ekoby** [comment]
done
