### ISSUE TITLE
Update references to ZITI_EDGE_CONTROLLER_API

### ISSUE THREAD

**Issue by gberl002** [openziti/ziti#650]
There are three references in quickstart files that are using ZITI_EDGE_CONTROLLER_API
The quickstart local (no docker) documentation references ZITI_EDGE_CONTROLLER_API (possibly other references in doc)

Any references to ZITI_EDGE_CONTROLLER_API should be updated to ZITI_EDGE_CTRL_ADVERTISED as this change was made in commit 3ca53eca8e8a186242fa1505654f2286aa77c136

**Comment by arunbingari** [comment]
I would like to work on this ! Please assign me !

**Comment by gberl002** [comment]
@arunbingari This one is being worked on as part of a quickstart cleanup I'm working on. The variable is being renamed, so it will be fixed in the process. Sorry about that, I'll update this and tie it to my branch.
