### ISSUE TITLE
Update CLI script M1 Support when github actions allows

### ISSUE THREAD

**Issue by gberl002** [openziti/ziti#652]
Currently github actions don't support pushing darwin arm distros. The CLI script currently works around this by pulling the darwin amd distro. Once github actions supports darwin arm the CLI script will need to be updated to pull the correct distro.

Appropriate build scripts will need to be updated as well so we actually push a darwin arm distro

https://github.com/actions/runner/issues/805

**Comment by mjtrangoni** [comment]
https://github.blog/changelog/2024-01-30-github-actions-macos-14-sonoma-is-now-available/
