### ISSUE TITLE
docker-compose down/up removes #public attribute from edge-router

### ISSUE THREAD

**Issue by dovholuknf** [openziti/ziti#663]
right now everytime you "up" docker-compose it'll delete/recreate the edge router... That's "fine" but not ideal whatsoever. Update the docker-compose environment (and any other environment similarly impacted) to not delete/recreate the edge router for 'no reason'. Check if it exists instead - or something else smarter.

**Comment by gberl002** [comment]
Fixed by commit 251806d43b0e18e8fb02480db2e1c9d430d46080 and PR https://github.com/openziti/ziti/pull/670
