### ISSUE TITLE
Broken link in README.md

### ISSUE THREAD

**Issue by RodneyRichardson** [openziti/ziti#694]
https://github.com/openziti/ziti#getting-started-with-ziti

The link "[up-and-running quickstart guides](https://github.com/openziti/ziti/blob/release-next/~/ziti/quickstarts/quickstart-overview.md)" doesn't exist (404 error).

**Comment by dovholuknf** [comment]
Thanks. that doc is quite stale. I'll update that link and read the rest of that page for anything else stale
