### ISSUE TITLE
Add port check to quickstart

### ISSUE THREAD

**Issue by gberl002** [openziti/ziti#706]
It would be nice to have a command to check if all the necessary quickstart related ports are available so the install doesn't fail. This could be either a command (that would be applied to `ziti-doc` repo) that's copy/pasted or even better, added to `expressInstall` and maybe a reference on how to change the port (in a case where the user cannot free it for the install).

**Comment by avinilcode** [comment]
@gberl002 Can i work on this? Please assign it to me.

**Comment by dovholuknf** [comment]
Sure thing. You'll want to add a function to `ziti-cli-functions.sh`. It probably should just make sure nothing else is running on the configured ports before running. You should be able to test failures by using `nc` to hold up the port before trying expressInstall

**Comment by avinilcode** [comment]
I will ask there any questions around it. Thanks

**Comment by plorenz** [comment]
Hey @avinilcode, I'm going to unassign this. I see you've got another issue on the ziti project you're also working on. If someone picks this up, I'll ping you to see if you've got some work to share before hand.

**Comment by avinilcode** [comment]
@dovholuknf Can you please tell me, port number 6262,1280,3023 and 10000 is it exhaustive list of ports that are being used in this project?

**Comment by dovholuknf** [comment]
Yes, you should check `ZITI_EDGE_CONTROLLER_PORT` not 8441.

**Comment by avinilcode** [comment]
Understood, working on it

**Comment by avinilcode** [comment]
@dovholuknf  Please review my PR and let me know
