### ISSUE TITLE
ziti-router version command misbehaviour

### ISSUE THREAD

**Issue by sabedevops** [openziti/ziti#712]
Running `ziti-router version` now prints additional text to stderr, even when not writing to a tty. This additional text creates the need for additional handling under certain circumstances, for example, when using configuration management systems that don't separate command output streams. This change was introduced in #647, below:

https://github.com/openziti/ziti/blob/release-next/ziti/cmd/ziti/util/updates.go#L56

Possible options for improvement:
1) Move this text to it's own command (e.g. `check-update`)
2) Move this text to it's own command flag (e.g. `version --check-update`)
3) Don't print unless printing to a tty
4) Add a suppression flag (e.g. `version --quiet` or `version --short`)

**Comment by qrkourier** [comment]
```bash
❯ ./ziti-router version >/dev/null

*********************************************************************************

An update with v0.26.3 is available for ziti-router v0.26.2 from 
https://github.com/openziti/ziti/releases/latest/

*********************************************************************************
```
