### ISSUE TITLE
Clean up ziti quickstart

### ISSUE THREAD

**Issue by gberl002** [openziti/ziti#746]
Due to repeated additions, enhancements, etc. the quickstart file has grown quite large and should be reviewed for simplification, cleanup, and general functionality. Preferably this would be done _after_ we have quickstart tests in place to ensure it isn't broken during the refactor.

Do remember to check documentation and update as necessary.

Also, the comment referenced below should be addressed regarding the possible values that should be covered in the DNS and IP allow lists.

> Did you cover all the possible variables (compared to .env it looks like a couple are missing if that was your intent)
> _Originally posted by @smilindave26 in https://github.com/openziti/ziti/pull/743#discussion_r889725031_

**Comment by ekoby** [comment]
@qrkourier says we can close
