### ISSUE TITLE
Allow configuration to be set dynamically

### ISSUE THREAD

**Issue by dovholuknf** [openziti/ziti#751]
Right now all configuration is done statically in a config file. That's served us well but it would be useful to be able to change values dynamically. If not all values, certain values we deem "customizable".

An example of this is the time a jwt token is valid for. It used to default to 5m which is just too little, soon changing to 180m. What if someone wanted this to be 24h or 7d etc.

We should allow configuration to be changed dynamically. It should also be persistent and not require a restart when done this way

**Comment by gberl002** [comment]
Relates to https://github.com/openziti/ziti/issues/748

**Comment by ekoby** [comment]
keep it

**Comment by ekoby** [comment]
maybe just add file watching of config

**Comment by smilindave26** [comment]
general very good idea, but deferring as we won't address in near term
