### ISSUE TITLE
Make linux client available through repos

### ISSUE THREAD

**Issue by gooseleggs** [openziti/ziti#772]
I would be great if the Linux clients were available through repos, such as PPA for Debian related and YUM for Redhat versions.  This will enable normal update processes to include any updates to these clients/servers and reduce ongoing administration of the client infrastructure.

**Comment by dovholuknf** [comment]
Yep. It's in the works. No ETA but hopefully soon

**Comment by qrkourier** [comment]
@gooseleggs Which would be more immediately valuable to you, `yum` or `apt` repo?

**Comment by gooseleggs** [comment]
For me, neither as I use docker and it has an update mechanism.  Since been talking about Windows updates, my mind naturally wondered and couldn't find reference to it.

**Comment by qrkourier** [comment]
Here is a link to the new documentation about installing the Linux packages: https://openziti.github.io/ziti/clients/linux.html#installation-and-upgrade
