### ISSUE TITLE
Need better error handling when github rate limit reached

### ISSUE THREAD

**Issue by gberl002** [openziti/ziti#797]
During express install, there are a few calls to github (I believe two per default install and more if you set a specific version to download). Github's API has a default rate limit of 60 calls per hour and, if reached, the ziti install will return `null` as the ZITI_BINARIES_VERSION to be downloaded. 

This install will continue to try and download with the null value, we should add a check for the version and halt the install while explaining what the issue may be and how to check.

With regards to how to check:
Run this command: `curl -I https://api.github.com/users/octocat`
And read the `x-ratelimit-remaining` field.
If the remaining calls is 0 then copy the value from the `x-ratelimit-reset` field and use a converter (such as http://www.epochconverter.com/) to find out when it will reset and more install attempts can be made.

This shouldn't happen often but we should provide better feedback to the user in the event that this does occur.

**Comment by ekoby** [comment]
done
