### ISSUE TITLE
IP-only controller adds IP to DNS of SANS

### ISSUE THREAD

**Issue by dovholuknf** [openziti/ziti#811]
user on discourse had a problem adding a second router to an "IP only" quickstart install. See discourse for details https://openziti.discourse.group/t/creating-certs-for-a-remote-private-router/694/8

It looks like when the environment doesn't have an external DNS (AWS does, OCI does not) and you set the external_dns to the external_ip, the cert that is generated will (of course) have an IP address added as a DNS entry. If the external_dns == the external_ip, we should not add the IP address as a DNS entry in the sans

**Comment by gberl002** [comment]
Fixing https://github.com/openziti/ziti/issues/812 _should_ fix this but double check after fixing to be sure
