### ISSUE TITLE
IP-only edge-router adds IP to DNS of SANS

### ISSUE THREAD

**Issue by dovholuknf** [openziti/ziti#812]
When using the external ip address as the EXTERNAL_DNS - as one does with OCI - the edge-router certs get created with a SANS of  the IP. example "DNS: xxx.xxx.xxx.xxx". 

When the EXTERNAL_DNS is the same as the EXTERNAL_IP - the quickstart should know better and handle that

![image](https://user-images.githubusercontent.com/46322585/183318346-29c91bfd-8ac3-4e0c-90f8-d9b9e0acbcab.png)

Watch the process here https://youtu.be/U4Me85ITLiQ

**Comment by gberl002** [comment]
Fixing https://github.com/openziti/ziti/issues/811 _should_ fix this but double check after fixing to be sure

**Comment by qrkourier** [comment]
duplicated by https://github.com/openziti/ziti/issues/1993
