### ISSUE TITLE
Document HA Cluster setup/configuration

### ISSUE THREAD

**Issue by plorenz** [openziti/ziti#819]
Document HA cluster setup well enough that others can work on HA development. 
Going to add a separate bug for more complete end-user HA documentation.

**Comment by abvaidya** [comment]
Yes please.

**Comment by dovholuknf** [comment]
Hi @abvaidya - @plorenz is working on implementing HA support as we speak! It'll be coming out soon! Keep an eye on this issue, welcome to OpenZiti
