### ISSUE TITLE
Perhaps "Zitify" is not the best marketing verb

### ISSUE THREAD

**Issue by jfxio** [openziti/ziti#832]
Hi. I listened to Clint Dovholuk's DeveloperWeek Cloud's talk. Ziti looks useful, we'll be giving it a whirl, but please, please on your website, change "Zitify your application". It scans as "Zit-ify your application". I don't want to turn my application into a giant puss-filled pimple ;-)

**Comment by dovholuknf** [comment]
bahahahahahahahah - the funniest part is that you're not the first person to notice that. Sounds like __something__ must be done. :)

**Comment by ekoby** [comment]
we use ziti-enabled or ziti-embedded more now
