### ISSUE TITLE
ZITI_EDGE_ROUTER_RAWNAME is not stored in .env output file

### ISSUE THREAD

**Issue by gberl002** [openziti/ziti#882]
ZITI_EDGE_ROUTER_RAWNAME is not stored in .env output file so if the file needs to be sourced and you attempt to start the edge router using `startExpressEdgeRouter` it will fail because the name is blank.

**Comment by ShivamGarg2910** [comment]
@gberl002 , can you share more details about the issue and how to reproduce?
It needs to be added in quickstart/docker, right?

**Comment by gberl002** [comment]
It needs to be added to quickstart when the env file is printed out. Specifically the `generateEnvFile` and `ziti_createEnvFile` functions, the `ziti_createEnvFile` function should output any env var starting with `ZITI_` but the value of `ZITI_EDGE_ROUTER_RAWNAME` must not have been set before the quickstart script is calling this function because the .env file is missing this value.

It should also be checked in docker to see if this value is written to the env file or not. Docker uses the quickstart functions but does not run the express install function so the docker situation might be different.

**Comment by gberl002** [comment]
Sorry to do this @ShivamGarg2910 but this is somewhat of a pressing issue so I went ahead and submitted a fix for it. Are you looking to help out on something particular or just looking for some easy bug fixes? I can help point you to something if I know a little more.
