### ISSUE TITLE
Publish the quickstart container on release

### ISSUE THREAD

**Issue by dovholuknf** [openziti/ziti#898]
Right now, the publishing of the quickstart container is manually accomplished. We should publish the quickstart container along with other artifacts

a new github action is created that will either:
* after a successful release of the `ziti` CLI:
  * ~~create/update a git tag named "quickstart-latest" set to the HEAD of main (as long as the release is published from main)~~
  * run a workflow that publishes a new container image to hub.docker.com that is aligned to the version of `ziti`
    aka if v0.30.0 of the `ziti` CLI is published, two container image tags will be published:
      * `openziti/quickstart:0.30.0`
      * `openziti/quickstart:latest`
* on merge to release-next with a PR that has been labeled: "quickstartrelease"
  * create/update a git tag named "quickstart-latest" set to the HEAD of release-next
  * run a workflow that publishes a new container image to hub.docker.com that is aligned to the __LATEST__ version of `ziti` but with the github commit sha appended to it.
    aka if 0.30.0 of the `ziti` CLI is the __LATEST__ published, two container image tags will be published:
      * `openziti/quickstart:0.30.0-${GITCOMMITSHA}`
      * `openziti/quickstart:latest` pointing to `openziti/quickstart:0.30.0-${GITCOMMITSHA}`
* A PUBLISHING.md will be created in /quickstart that covers and explains this action, how it works and any other relevant information as needed

**Comment by qrkourier** [comment]
> create/update a git tag named "quickstart-latest" set to the HEAD of main (as long as the release is published from main)

We can skip this because we're already setting Git tag `quickstart-latest` to the HEAD of `release-next` which is always the same or newer Git revision than `main`. That is, there's no edge case wherein `main` is newer than `release-next`.

**Comment by qrkourier** [comment]
I edited the spec to drop the leading `v` in the container image tag examples to conform with the tag name convention we're using in container image repository `openziti/quickstart`.

**Comment by qrkourier** [comment]
@dovholuknf Pushing to release-next will produce [quickstart release container images like this](https://hub.docker.com/layers/kbinghamnetfoundry/quickstart/0.30.3-d64955ad/images/sha256-cccd42284e4d59d826867411b7aa7babbbc0a44959b7c02cb4e8e7b4095952d0?context=explore) with the prior (real) ziti release inside (not the experimental `ziti` CLI built from the branch), e.g., 0.30.3 in this case.

**Comment by dovholuknf** [comment]
merging to release next, __with__ the specified lablel should produce a 'latest' docker image from the 'actual latest' deployed version of ziti (not built from release-next). I assume that's what you mean by "images like this" and when you reference 0.30.3. 

merges alone should not trigger it

**Comment by qrkourier** [comment]
I'm [fishing for ideas](https://github.com/orgs/community/discussions/67520) in GitHub Community Discussions because I haven't found a way to evaluate pull request labels in the push event to release-next.
