### ISSUE TITLE
docker (no compose) can fail if the ziti.env is not written

### ISSUE THREAD

**Issue by dovholuknf** [openziti/ziti#901]
Had a user sudo to root before running the docker (no compose) quickstart. Things appeared fine except when they tried to add the edge-router it failed an produced this message over and over:
```
waiting for https://
waiting for https://
waiting for https://
waiting for https://
waiting for https://
```

After working with the user it turns out they had followed the quickstart instructions as root. This means the empty ziti.env file was written and owned by root. When the docker file ran, it failed to write into that file because the docker container uses the `ziti` user (user 1000).

Warn the user, exit, do something if the ziti.env file is not written to before trying to run the router. It might be something the controller does?

**Comment by ekoby** [comment]
does not seem important now, re-open if needed later
