### ISSUE TITLE
ZITI_HOME not properly set in some scenarios

### ISSUE THREAD

**Issue by gberl002** [openziti/ziti#907]
The `setupZitiHome` function is called from a few locations within the quickstart script but it doesn't check for the value of ZITI_NETWORK despite depending on that value.

If called after say, `unsetZitiEnv` is called, the resulting value is missing an expected directory name and because of which, includes a double path separator. 

This needs to check the value of ZITI_NETWORK first and if not set, set it (likely to the default which should be `$(hostname)`)

In the following, notice the paths are different but also, there is a trailing path separator which causes an issue for other paths that append onto this path.

Examples:
When ZITI_NETWORK is properly set, ZITI_HOME is: 
```/Users/geoffberl/.ziti/quickstart/MacBook-Pro.local```
When ZITI_NETWORK is not properly set, ZITI_HOME is:
```/Users/geoffberl/.ziti/quickstart/```

This line is the main point of failure (depending on whether or not ZITI_NETWORK is blank)
```export ZITI_HOME="${HOME}/.ziti/quickstart/${ZITI_NETWORK-}"```

**Comment by qrkourier** [comment]
I see we're assigning `ZITI_NETWORK` to the default value of `$(hostname)` in several places. We could add another assignment for this scenario.
