### ISSUE TITLE
ziti enroll fails to add CA bundle when using a publicly trusted PKI

### ISSUE THREAD

**Issue by dovholuknf** [openziti/ziti#915]
if the controller uses a cert issued by a CA trusted by the OS, the CA bundle from the controller is not fetched which produces an identity with no `ca` entry.

This _usually_ causes problems with edge clients connecting to the data plane, as the certificate presented by the routers is _usually_ from the private PKI. 

If no `ca` entry exists in the identity file, the trust root cannot be established and the client won't successfully connect to routers.

Change the `ziti` CLI to always pull and include the `ca` bundle during the enrollment process.

**Comment by qrkourier** [comment]
Agree that enrollment should always fetch the well known bundle and insert in `id.ca` as long as edge SDKs fall back to verifying server certs with the OS trust store when the bundle doesn't contain the issuer's CA cert. That doesn't appear to be universally the case at this time, however. Rather, the C-SDK, at least, will fail to verify the server cert when `id.ca` is present in the identity context and the issuer's CA cert isn't in the bundle, as is the case for a server certificate issued by a public authority like Let's Encrypt. 

In summary, today it is presumed that all routers' TLS and WS bindings and the controller's edge-client API present only server certificates that can be verified by the OS trust store and that `id.ca` must not be present in the context i.e. if any one of those server certificates is publicly verifiable then they must all be publicly verifiable. 

`ziti-edge-tunnel enroll` deviates from this pattern by always inserting `id.ca`, even when it's unnecessary, thereby preventing the identity from verifying server certificates from a public CA. I tested this by pruning the `id.ca` property from the config and confirming the tunneler functions normally thereafter.

**Comment by andrewpmartinez** [comment]
Based on your testing, the C-SDK tries the CA bundle from the identity and then the OS bundle.

The GO SDK tries the identity bundle and then gives up.

I don't know what the SDKs that don't use the C-SDK do (i.e. JVM).

It seems like to support public CAs we have to adopt the fall back pattern.

**Comment by andrewpmartinez** [comment]
> In that case, SDKs could refresh their embedded CA bundle by fetching the latest if verification fails.

Yes, I agree. The well-known CA store should be hit again in that scenario.

**Comment by ekoby** [comment]
> > In that case, SDKs could refresh their embedded CA bundle by fetching the latest if verification fails.
> 
> Yes, I agree. The well-known CA store should be hit again in that scenario.

the problem is if your CA bundle is expired SDK would fetch CA bundle from untrusted source

**Comment by andrewpmartinez** [comment]
> the problem is if your CA bundle is expired SDK would fetch CA bundle from untrusted source

Won't help in that scenario but it will help if the controller has been reconfigured with a new CA bundle. Expiration is an entirely different problem.

**Comment by ekoby** [comment]
> > the problem is if your CA bundle is expired SDK would fetch CA bundle from untrusted source
> 
> Won't help in that scenario but it will help if the controller has been reconfigured with a new CA bundle. Expiration is an entirely different problem.

isn't it the problem though? if controller has new CA bundle --> has cert issues with new bundle --> SDK with old bundle cannot validate it and download new bundle

**Comment by qrkourier** [comment]
Relatedly, [Go SDK PR to change enroll behavior](https://github.com/openziti/sdk-golang/pull/342) to always fetch Ziti trust bundle.

**Comment by qrkourier** [comment]
For reference, a writeup about how to align alt server certs and SDK configs: https://openziti.github.io/guides/alt-server-certs

**Comment by andrewpmartinez** [comment]
> > > the problem is if your CA bundle is expired SDK would fetch CA bundle from untrusted source
> > 
> > 
> > Won't help in that scenario but it will help if the controller has been reconfigured with a new CA bundle. Expiration is an entirely different problem.
> 
> isn't it the same problem though? if controller has new CA bundle --> has cert issued with new bundle --> SDK with old bundle cannot validate it and download new bundle

I don't think so. An external CA could be added (i.e. through 3rd Party CAs or static configuration). If the controller's non-alternate-server-cert is being changed to a different CA that would require 1) the controller to publish the new CA to trust first 2) the SDKs would have to support refreshing the CA bundle lastly 3) once all/enough SDKs trust the new CA the server cert can be changed.

**Comment by ekoby** [comment]
superseded by future trust bundle work
