### ISSUE TITLE
Automated various deployments

### ISSUE THREAD

**Issue by dovholuknf** [openziti/ziti#927]
We have or want a few different deployment mechanisms and it would be useful to have all these various deployments not only documented but automated. these include:

* rancher support
* redhat support
* openziti/quickstart
* packaging of `ziti` to other package managers for the likes of debian (linux), fedora (linux), chocolatey (win), scoop (win), homebrew, brew, snap whatever

**Comment by ekoby** [comment]
open individual issues as needed
