### ISSUE TITLE
Password prompt hangs with ZSH running docker quickstart

### ISSUE THREAD

**Issue by gberl002** [openziti/ziti#933]
The new feature asking the user if they would like to use the generated password or provide their own is unresponsive to input from ZSH. No matter what input is given the script hangs.

Even more bizarre, if you don't type anything and just press enter, it actually does print the INFO line that follows stating that it will be using the generated password, but then hangs which is very strange. If `y` or `n` are sent, no INFO message follows, it just hangs.

I was able to circumvent this issue by using BASH instead.

**Comment by qrkourier** [comment]
I couldn't reproduce this with Zsh v5.8 on a fresh install of Debian Bullseye. I followed the instructions in [the hosted quickstart](https://openziti.github.io/docs/quickstarts/network/hosted/). I tried answering `y` and `n` and got the expected result for both. I got the expected `y` default result by pressing <enter> at the blank prompt.

**Comment by gberl002** [comment]
Interesting... I'm running MacOS with Oh My ZSH so it's possible it's very specific to OMZSH. I'll try it with Mac's default ZSH when I get a chance and see what happens.

**Comment by dovholuknf** [comment]
on my M1 mini, it does not hang forever. I'm also using OMZSH. I do however get bad CPU arch
![quickstart](https://user-images.githubusercontent.com/46322585/210861629-11db71fa-2f79-4e3b-b448-cb6ac22b93ee.gif)

**Comment by gberl002** [comment]
This must have been a very strange fluke, I'm unable to reproduce this on my machine, which has since been restarted so maybe that fixed whatever was causing it. I'll close this issue for now.
