### ISSUE TITLE
ziti-router creates multiple  IPs for same DNS name

### ISSUE THREAD

**Issue by jlin-nf** [openziti/ziti#960]
1. Creates multiple services with same intercept DNS name.
2. Create bind service-policy for all services in step 1 to the same identity (endpoint on an Edge-Router)
3. Check the intercepts on the endpoint:
$ zt-intercepts
Chain NF-INTERCEPT (1 references)
target     prot opt source               destination
TPROXY     udp  --  0.0.0.0/0            100.64.0.3           /* testziti-dns3 */ udp dpt:53 TPROXY redirect 127.0.0.1:40928 mark 0x1/0x1
TPROXY     tcp  --  0.0.0.0/0            100.64.0.2           /* testziti-dns1 */ tcp dpt:80 TPROXY redirect 127.0.0.1:45787 mark 0x1/0x1
TPROXY     tcp  --  0.0.0.0/0            100.64.0.1           /* testziti-dns2 */ tcp dpt:443 TPROXY redirect 127.0.0.1:40217 mark 0x1/0x1

$ ping testziti.james.net
PING testziti.james.net (100.64.0.1) 56(84) bytes of data.
64 bytes from 100.64.0.1: icmp_seq=1 ttl=64 time=0.081 ms

So, only one of the service works.

**Comment by jo-te** [comment]
Any progress on this? This is still an issue as of `ziti-router:1.2.2` and prevents using a ziti-router as sidecar for docker containers when multiple ports need to be proxied.

**Comment by qrkourier** [comment]
@jo-te Another approach is to define a single service with multiple ports instead of multiple services, each with one port.

**Comment by jo-te** [comment]
> @jo-te Another approach is to define a single service with multiple ports instead of multiple services, each with one port.

Yes I thought about this option, I see how this can work with forwarding the ports (e.g. 80–>80,443–>443) but is it also possible to define a single service with different ports on intercept and host (e.g. 80–>9080,443–>9443)?

**Comment by jo-te** [comment]
> > is it also possible to define a single service with different ports on intercept and host (e.g. 80–>9080,443–>9443)?
> 
> 
> 
> Yes. There's no coupling between the intercepted port and the server target port in the hosting config unless your host config is set to forward the intercepted port, i.e., send to the same target port that was intercepted.

I see. Is there anywhere an example config fur such a setup? Because until now I found only single port setups and don't really know how to configure this correctly... :/
Would also feel a bit cleaner than always defining a http and a https service.

**Comment by qrkourier** [comment]
@jo-te Here's an example of a pair of service configs, one for each end of the service: an `intercept.v1` and a `host.v1` config bound to a Ziti service (one service with two configs). The config schema is expressive enough that you will not need redundant intercept or redundant host configs. Or, at least, I haven

I'll demonstrate forwarding the same port that was intercepted, which _does_ couple the port number on both ends of the service, because it seems to suit the case you're describing where a single target server is listening on 80,443/tcp.

The service's `intercept.v1` config:

```bash
ziti edge create config "test-intercept" intercept.v1 \
    '{"portRanges":[{"high":80,"low":80},{"high":443,"low":443}],"addresses":["svc.test.ziti.internal"],"protocols":["tcp"]}'
```

The config entity this creates is represented in the API like this, where the configTypeId is that of the `intercept.v1` type.

```json
{
  "name": "test-intercept",
  "configTypeId": "g7cIWbcGg",
  "data": {
    "portRanges": [
      {
        "high": 80,
        "low": 80
      },
      {
        "high": 443,
        "low": 443
      }
    ],
    "addresses": [
      "svc.test.ziti.internal"
    ],
    "protocols": [
      "tcp"
    ]
  },
  "tags": {}
}
```

Likewise, here's a CLI example for creating a `host.v1` config allowing the above intercept config's ports: 80,443/tcp, and forwarding to the same port that was intercepted.

```bash
ziti edge create config "test-host" host.v1 \
    '{"protocol":"tcp","address":"web.lab.private","forwardPort":true,"allowedPortRanges":[{"high":80,"low":80},{"high":443,"low":443}],"httpChecks":[],"portChecks":[]}'
```

```json
{
  "name": "test-host",
  "configTypeId": "NH5p4FpGR",
  "data": {
    "protocol": "tcp",
    "address": "web.lab.private",
    "forwardPort": true,
    "allowedPortRanges": [
      {
        "high": 80,
        "low": 80
      },
      {
        "high": 443,
        "low": 443
      }
    ],
    "httpChecks": [],
    "portChecks": []
  },
  "tags": {}
}
```

Once both configs are created, you can make a service with them.

```bash
ziti edge create service "test-service" \
    --role-attributes "test-services" \
    --configs "test-intercept,test-host"
```

API representation of the service:

```json
{
  "createdAt": "2024-12-03T22:23:22.043Z",
  "id": "6BrZv2ZEkSh1OZhtTaPTl2",
  "tags": {},
  "updatedAt": "2024-12-03T22:23:22.043Z",
  "config": null,
  "configs": [
    "2HlNxAUt69B0IcuIXzwtNN",
    "6sno9dNvCpPzpodntQkPua"
  ],
  "encryptionRequired": true,
  "maxIdleTimeMillis": 0,
  "name": "test-service",
  "permissions": [
    "Invalid"
  ],
  "postureQueries": [
    {
      "isPassing": true,
      "policyId": "dummy invalid policy: no posture checks defined",
      "policyType": "Invalid",
      "postureQueries": []
    }
  ],
  "roleAttributes": [
    "test-services"
  ],
  "terminatorStrategy": "smartrouting"
}
```

**Comment by jo-te** [comment]
@qrkourier Thanks for your extended reply.
I'm still unsure how it would look like if no port forwarding is used, but I know that this is not in any sense related to this issue and I will try to find out when I can get my hands back on this.

**Comment by qrkourier** [comment]
We can discuss it further in the forum: https://openziti.discourse.group/ :slightly_smiling_face: I'm @qrkourier there too.
