### ISSUE TITLE
Stop recreating router config in docker

### ISSUE THREAD

**Issue by gberl002** [openziti/ziti#963]
While the run-router script _does_ check if the router exists and doesn't recreate it, it still recreates the config file every time. The config file should not be recreated when a container is brought down and back up.

**Comment by dsukruth** [comment]
According to [](https://github.com/docker/compose/issues/9600 )

changing to v2.15.0 might fix the issue.

**Comment by dsukruth** [comment]
[](https://github.com/docker/compose/issues/9600)

might help to fix the issue

**Comment by dsukruth** [comment]
[docker compose up recreates running container that does not have their configs changed in docker-compose.yml](https://github.com/docker/compose/issues/9600)

might help to fix the issue

**Comment by qrkourier** [comment]
The `openziti/ziti-router` image will generate a config unless it exists.

Example:

```bash
# create the router, saving the enrollment token to a file
ziti edge create edge-router "router1" \
   --jwt-output-file=./router1.jwt

# fetch the compose file for the ziti-router image
wget https://get.openziti.io/dist/docker-images/ziti-router/compose.yml

ZITI_ENROLL_TOKEN="$(<./router1.jwt)" \
ZITI_CTRL_ADVERTISED_ADDRESS=ctrl.127.21.71.0.sslip.io \
ZITI_CTRL_ADVERTISED_PORT=1280 \
ZITI_ROUTER_ADVERTISED_ADDRESS=router1.127.0.0.1.sslip.io \
ZITI_ROUTER_PORT=3022 \
    docker compose up
```

from the README: https://github.com/openziti/ziti/tree/main/dist/docker-images/ziti-router#readme
