### ISSUE TITLE
Stand up a stand alone router within docker

### ISSUE THREAD

**Issue by gooseleggs** [openziti/ziti#967]
I was wanting to stand up an edge router on a separate host using docker.  There is no easy way to achieve this.  To this end, I have written a pull request to allow this capability.  

I have added it to the quickstart docker container, and may alternatively be created as a standalone image.  However, I went with quickstart as people testing may want this capability, and it is relatively easy to achieve this.

This was borne out of https://openziti.discourse.group/t/setup-new-edge-router-on-a-separate-host/974 and https://openziti.discourse.group/t/edge-router-different-host-via-docker/986.

The script used to provide this functionality does not require the `ziti.env` file at all.  Currently, when moving components around different hosts, it was required to take the ziti.env file with you.  This made it cumbersome to stand up.

**Comment by ekoby** [comment]
fixed in #966
