### ISSUE TITLE
Allow version update to be opt-in, or opt-out... 

### ISSUE THREAD

**Issue by dovholuknf** [openziti/ziti#984]
https://github.com/openziti/ziti/pull/546 introduced an HTTP request at startup to github's api. It's probably a good idea to allow people  to opt IN, or OUT of this functionality...

I think we should let people opt in, instead of doing it by default. Remove the automatic update checking from default behavior but let people opt IN if they provide an environment variable/flag

**Comment by qrkourier** [comment]
Cross-linking another issue with similar ideas for improving this behavior: https://github.com/openziti/ziti/issues/712
