### ISSUE TITLE
"ziti create config router edge" doesn't know about --tunnelerMode proxy

### ISSUE THREAD

**Issue by qrkourier** [openziti/ziti#987]
```bash
    ziti create config router edge \
    --routerName router01 --tunnelerMode proxy
error: Unknown tunneler mode [proxy] provided, should be "none", "host", or "tproxy"
```

**Comment by qrkourier** [comment]
```yaml
listeners:
  - binding: tunnel
    options:
      mode: proxy
      services: 
        - zedsDemoHttpHttpbin:8080
```

from: https://docs.openziti.io/docs/reference/configuration/router/#tunnel-listeners

**Comment by qrkourier** [comment]
This bug still exists in 0.30.0.

**Comment by qrkourier** [comment]
This raises the question, "Are the allowed modes hard-coded?" If so, is there a way to read the actually-allowed modes from another part of this project instead of hard-coding them? They won't change often, but if there's an easy way to do that it seems better.

**Comment by qrkourier** [comment]
@gberl001 I was able to reproduce this issue in 0.32.2.

**Comment by dovholuknf** [comment]
It's important to remember that this function is not meant to be a comprehensive, one-stop-shop for all options to configure all the things. It's intended to be a "get you close, you can modify it if it's missing" sort of utility.
